### ISSUE TITLE
spurious validity errors

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#100]
on my machine (Ubuntu 15.04) I get `validity error` messages on stderr:

```
maeder@lati:/var/data/localmh/MathHub/smglom/mv$ run-latexml.sh source/piecewise.de.tex 
element XMApp: validity error : ID cvar.6 already defined
element XMTok: validity error : ID piecewise.de.definition3.CMP1.p3.m3.1 already defined
element XMApp: validity error : ID cvar.5 already defined
element XMApp: validity error : ID cvar.4 already defined
element XMTok: validity error : ID S0.Ex1.m1.1 already defined
element XMApp: validity error : ID cvar.0 already defined
element XMApp: validity error : ID cvar.1 already defined
element XMApp: validity error : ID cvar.2 already defined
element XMApp: validity error : ID cvar.3 already defined
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/mv/source/piecewise.de.omdoc
```

On ash (Debian 8 (jessie)), there are no errors shown. The output created is identical on both machines, so the messages could be simply ignored, but they are still irritating.

(An old related issue seems to be http://www.cpantesters.org/cpan/report/ba10553c-8029-11e4-b744-f4345ef060ad )

The script to run latexml is https://github.com/KWARC/MMT/blob/svn-mirror/src/mmt-stex/run-latexml.sh.

**Comment by dginev** [comment]
Oh wow, 15.04 is out?

If this is another breaking change of libxml2 I will have to find a place to channel anger. It took forever to resolve a breaking valdiation problem with the newer version of libxml2 for the 0.8 release of LaTeXML back in November 2014, hopefully we are not hitting that again.

**Comment by cmaeder** [comment]
My machine has `libxml2:amd64: /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.2` whereas ash has
`libxml2.so.2.9.1`. I'll try, if I can replace my libxml2.

**Comment by cmaeder** [comment]
Yes, I could `apt-get install libxml2=2.9.1+dfsg1-4ubuntu1` and got:

```
maeder@lati:/var/data/localmh/MathHub/smglom/mv$ run-latexml.sh source/piecewise.de.tex 
Warning: XML::LibXML compiled against libxml2 20902, but runtime libxml2 is older 20901
Warning: XML::LibXML compiled against libxml2 20902, but runtime libxml2 is older 20901
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/mv/source/piecewise.de.omdoc
```

**Comment by cmaeder** [comment]
I had to add `deb http://de.archive.ubuntu.com/ubuntu/ utopic main` to `/etc/apt/sources.list` to get the older `libxml2`. However, the version for `libxml-libxslt-perl` is identical for utopic and vivid, namely  `1.92-1build1`.

**Comment by dginev** [comment]
Well this will bring back horrible memories. CC-ing @brucemiller here, so that he knows to expect a native LaTeXML issue soon. I am happy I am yet to update my Ubuntu installation.

**Comment by dginev** [comment]
And so I took the plunge and upgraded to 15.04. Good news for @cmaeder : my setup 1) can't run TAP at all and 2) segfaults when running latexmlc :>

I think my libxml just got completely disconnected from XML::LibXML during the upgrades. Will hunt down more tomorrow, will borrow this issue. @brucemiller : I am calling from the future, it ain't good :>

**Comment by cmaeder** [comment]
My software setup is done using https://gl.mathhub.info/meta/inf/tree/master/config/MMT
(see setupLocalMH.sh)

```
./setupSoftware.sh
./setupCpanm.sh
./setupLaTeXML.sh
```

**Comment by cmaeder** [comment]
@kohlhase @m-iancu How was `pine.eecs.jacobs-university.de:/var/data/localmh/sty` created? (I don't see a corresponding repository). Why is this directory needed (if it is at all)?

**Comment by kohlhase** [comment]
It has a couple of packages I did not know where to put otherwise.

**Comment by dginev** [comment]
CC-ing @brucemiller here since it's again related to the LaTeXML installation.

What had happened is that my cpanm-installed JSON::XS was out of sync with a system library, and it was segfaulting. I reverted to using the ```JSON::XS``` from the package manager, which worked like a charm. 

I am also successfully running make test under libxml 2.9.2, which means I can't reproduce the validity errors reported by @cmaeder, everything seems fine.

**Comment by dginev** [comment]
For now I am assuming the validity errors come from the libxml changes we already addressed for the last release.

**Comment by brucemiller** [comment]
Any chance that this is related to a few random failures on cpantesters? (i doubt it, but...)

**Comment by cmaeder** [comment]
`make test` does not produce the validity errors that I reported above. They are reported for our example `piecewise.de.tex` from `smglom/mv` (and for other examples).

**Comment by cmaeder** [comment]
> It has a couple of packages I did not know where to put otherwise.

see #102

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#23
