### ISSUE TITLE
modnl only works with creators

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#101]
For some reason latexml fails on 
```
\begin{modnl}{local-base}{zhs}
```
but works on 
```
\begin{modnl}[creators=Tianlin]{local-base}{zhs}
```
Both should work.

**Comment by angerhang** [comment]
I can't see any problem from my side. Can you show me an example and how you call latexml?

**Comment by angerhang** [comment]
I just ran `lmh omdoc ` on local-base without `creator`, and there was no problem.

```
latexml-result: success topology/latexml/local-base.zhs.omdoc
Worker[1]: Finished working on smglom/topology
```

Perhaps this issue can be closed.

**Comment by kohlhase** [comment]
OK, closing
