### ISSUE TITLE
additional .sty files

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#102]
I just realised the files pine.eecs.jacobs-university.de:/var/data/localmh/sty come from https://github.com/KWARC/localmh (see #100)

I suppose, I need to address them when calling latexml

**Comment by kohlhase** [comment]
yes, just add a ```--path```

**Comment by cmaeder** [comment]
I hope this is resolved by https://github.com/KWARC/MMT/commit/a7c33276c2ce99b360e614802f5b9ba542413365
