### ISSUE TITLE
Write etoolbox.sty.ltxml

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/sTeX#104]
When an etoolbox command sequence inside ``RawTeX``, latexml side will crash.

For example, ``mikoslides.cls.ltxml``

```latex
RawTeX('
\newrobustcmd\mhframeimage[2][]{%
  \metasetkeys{Gin}{#1}%
  \edef\mh@@repos{\mh@currentrepos}%
  \ifx\Gin@mhrepos\@empty%
    \frameimage[#1]{\MathHub{\mh@currentrepos/source/#2}}%
  \else%
    \frameimage[#1]{\MathHub{\Gin@mhrepos/source/#2}}%
  \fi%
}%
');
```

contains ``\newrobustcmd``, which causes the crash.

This issue originates from #103

**Comment by kohlhase** [comment]
We have two ways of handling this. Either using ```\newrobustcommand``` on the LaTeX side and ```\newcommand``` on the LaTeXML side (i.e inside the RawTeX). Or (preferred) directly implement ```\mhframeimage``` in LaTeXML.

**Comment by angerhang** [comment]
This is no longer applicable.
