### ISSUE TITLE
clean up info errors in SMGloM

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#106]
In https://github.com/KWARC/MMT/issues/29 @cmaeder reports SMGloM errors with the new errro veiewer http://ash.eecs.jacobs-university.de:8080/errorview.html (running latexml takes 20 hours). We should get the infos (CMP and srcref) sorted out. The are also reported in the MathHub error viewer (given the right settings), but that has a different run (I think). @m-iancu can give more info on this. 

Assigning to Hang for the moment, we should discuss this.

**Comment by m-iancu** [comment]
MathHub.info has a different run indeed. The infos are fairly harmless but many are probably easy to fix. Most are about missing source references. Also, the most common one in that list `Unexpected element label in CMP: div ` is actually irrelevant and I should remove it. I had added it for debugging somthing. It is safe to ignore it for now.

**Comment by kohlhase** [comment]
> Also, the most common one in that list Unexpected element label in CMP: div is actually irrelevant and I should remove it. I had added it for debugging somthing. It is safe to ignore it for now.

Ah, that is good to know, because that is not one I knew how to fix.

**Comment by kohlhase** [comment]
I am a bit surprised at the fact that we are getting infos about missing srcrefs on omdoc:imports. That is present on my local machine. I am wondering what version Christian used.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#22
