### ISSUE TITLE
sTeX light Tracker

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#112]
We want the sTeX bindings (```*.sty.ltxml```) with a light variant with which directly generates preloaded HTML5. For that we need to give every sTeX macro and environment a "light variant" that (ultimately) generates HTML5+RDFa instead of OMDoc. This is the format that MMT also generates from OMDoc, and on which JOBAD operates, so that the results of sTeX light are (at least partially) active documents.

The development should go to a new branch. There is an old branch concerned with the same development, but this has decayed; this needs to be cleaned up and the relevant pieces salvaged. 

We have the following partial issues

* modules light (see #113)
* omtext, statements, omdoc,  problem, sproof, hwexam light

Eventually, we want users to just choose the document class to get the OMDoc (sTeX) or preloaded HTML (sTeX light).  Therefore ```omdoc.cls.ltxml``` should set a switch (e.g. ```stex@omdoc```) that will decide between the sTeX and sTeX light macros. Let us see what we need to do for the case of the ```axiom``` environment from ```statements.sty.ltxml```

For the "heavy" version we keep the current version:
```
DefStatement('{axiom} OptionalKeyVals:omtext',
  "<omdoc:axiom "
  .   "?&GetKeyVal(#1,'id')(xml:id='&GetKeyVal(#1,'id')')()>"
  .   "?&GetKeyVal(#1,'title')(<dc:title>&GetKeyVal(#1,'title')</dc:title>)()"
 . "<omdoc:CMP>#body"
  . "</omdoc:axiom>\n");
```
and for the light version we do something like
```
DefEnvironment('{axiom}[]',
	       "<ltx:block class='ltx-axiom'>"
	       . "?#1(<ltx:text rel='omdoc:for' resource='##1'/>)()"
	       . "#body"
	      ."</ltx:block>");
```
Of course we still need to refine this (coordinate with @m-iancu) to generate the correct meaning (I think @m-iancu said that JOBAD uses html5 data attributes for the preloading). In this example we make use of the LaTeXML RDFa attributes, which are very very convenient for the task.

DISCUSS: what attribute set do we eventually want to use here? RDFa seems better supported by LaTeXML, maybe we can convert the preloading stuff to JOBAD form with a style sheet afterwards?

DISCUSS: what is the best way of making using the ```stex@omdoc```  switch?

**Comment by kohlhase** [comment]
We should start with ```statements.sty.ltxml``` as an example on another branch.

**Comment by angerhang** [comment]
So the approach that I am implementing right now is using `stex@omdoc` in all the packages that have sTeX specific primitives, macros and constructors... 

When we pass the `stex@omdoc` option to sTeX, `omdoc.cls.ltxml` also passes this option to the relevant packages in order to produce the desired HTML. 

As @kohlhase mentioned before, the current solution is likely to double the size of each package, instead of having to load `*-light.cls.ltxml` when we want to switch to the HTML workflow in the future, we only need to pass one option.

**Comment by angerhang** [comment]
I think this ticket along with #113 can be closed now due to the change of HTML generation.

#134 can be served as a general purpose issue tracker.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#41
