### ISSUE TITLE
latexml error "equals" on undefined

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#116]
On https://mathhub.info/MiKoMH/GenCS/logic/en/calculus-infrules.omdoc we have the error 

```
	/var/data/localmh/MathHub/MiKoMH/GenCS/source/logic/en/logical-system.sms#textrange(from=1;17,to=2;46)
	Can't call method "equals" on an undefined value at /var/data/localmh/ext/perl5lib/lib/perl5/LaTeXML/Core/KeyVals.pm line 85, <$IN> line 2.
	In \importmhmodule OptionalKeyVals:impor... from modules.sty.ltxml line 858
	 <= Core::Stomach[@0x44a4a70] <= Core::Gullet[@0x44a4b78] <= Core::Stomach[@0x44a4a70] <= ...
```
assigning to Hang, but @dginev can supervise?

**Comment by angerhang** [comment]
I couldn't duplicate the same error message on my local machine. 

I think the log file on MathHub webpage has not been updated yet.

On the error viewer, which has a newer version of sTeX, this error no longer exists.

**Comment by kohlhase** [comment]
@dginev could you have a quick look at this? This causes 500 fatal errors on MathHub.

**Comment by angerhang** [comment]
Maybe this bug was fixed after LaTeXML was merged with its upstream?

I did a clean installation of lmh on Thursday and now I got the following for ` MiKoMH/GenCS/latexml/logic/en/calculus-infrules.tex`
```
Driver file for pgf: \pgfsysdriver



Warning:not_parsed:METARELOP>POSTSUBSCRIPT MathParser failed to match rule 'Anything'
	Anonymous String#textrange(from=0;1,to=0;0)
	MathParser failed to match rule 'Anything'
	In "\@@use{\vdash_{arg:1}}"
	⊢[[METARELOP]]
	        > _{arg:1}[[POSTSUBSCRIPT]]

Conversion complete: 1 warning.

Post-processing complete: No obvious problems
```
@m-iancu can you help confirm this?

**Comment by angerhang** [comment]
This could have been fixed by recent changes made in LaTeXML, so it no longer applies, albeit feel free to reopen it if it comes back again.
