### ISSUE TITLE
regression: symtest does not work any more. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#117]
in all of the ```smglom/*/source/*.tex``` there are ```\symtest``` macros that are supposed to write out symbol tests. They no longer do that. I suspect it has something to do with the robustcommand change. 

It seems that the ```\if@importing``` is not false at the time as it should be: ```\@ifimporting``` should only be false during an ```\importmodule```. Please have a look.

**Comment by La-Stravaganza** [comment]
What is it supposed to be when I compile, for example, ``set.tex`` with ``lmh pdf set.tex``?

**Comment by kohlhase** [comment]
```LaTeX
\symdef{foo}{FOO}
\symtest{foo}{\foo}
``` 
is supposed to generate somthing like 
```
semantic macro \foo: FOO
``` 
into the PDF.

**Comment by La-Stravaganza** [comment]
I accidentally deleted one pair of curly brackets, now it is fixed. Please have a look at the pull request #119 .
