### ISSUE TITLE
Conversion to `ltx:p` messes with LaTeXML schema 

### ISSUE THREAD

**Issue by angerhang** [KWARC/sTeX#127]
During the modules light conversion process, we need to go through several steps to generate HTML, namely:

1. Convert the `tex` source file into `ltx+XMATH`.
2. Convert `ltx+XMATH` into `ltx+MathML or OpenMath`.
3. Lastly, use the post processor to generate the desired `HTML`.

In 013937c3512037838f28a1d3045233bbfa4c0b4b, I added the light version to the `definition` environment and I got stuck in the second stage. More specifically when I was trying to open up a `<ltx:p>` inside a `<ltx:block>`, LaTeXML complains: 
```log
Error:malformed:ltx:p <ltx:p> isn't allowed here
	/Users/yuancalvin/localmh/ext/sTeX/htmltest/test.tex#textrange(from=9;0,to=9;34)
	Currently in XMLDocument[140390366610096]<ltx:document _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." _ID_counter_p_="1" xmlns="http://dlmf.nist.gov/LaTeXML">...<ltx:para _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." class="theory" xml:id="p1">...<ltx:block _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." class="definition" xml:id="foo"/>
	In Core::Document[@0x7faf2c5b6930] /Users/yuancalvin/localmh/ext/sTeX/htmltest/test.tex#textrange(from=9;0,to=9;34)
	 <= \begin{definition} OptionalKeyVals:om... <= \begin{definition}[id=foo, for={bar}]... <= Core::Document[@0x7faf2c5b6930] <= ...
 0.05 sec)
```

Let's say we have a sample file:
```tex
\begin{module}[id=foo,creatos=miko]  
\begin{definition}[id=foo,for=bar]
testing 
\end{definition}    
\end{module}    
```

we get an output as below:
```xml
 <para class="theory" xml:id="p1" fragid="p1">
    <block class="definition" xml:id="foo" fragid="foo">
      <p xml:id="foo.p1" about="#foo.p1" stex:srcref="/Users/yuancalvin/localmh/ext/sTeX/htmltest/test.tex#textrange(from=9;0,to=11;16)" fragid="foo.p1">
testing 
      </p>
    </block>
  </para>
```

It should be valid with [LaTeXML-block schema](http://dlmf.nist.gov/LaTeXML/manual/schema/schema.module.LaTeXML-block.html), but I don't really know why LaTeXML thinks the document is malformed.

 @dginev can you comment on this?

**Comment by dginev** [comment]
Sure, LaTeXML p's aren't allowed in LaTeXML blocks, just as the schema says. You need to open a logical paragraph, ltx:para, first.

But since you are doing sTeX - why are you opening LaTeXML elements? Shouldn't you be manually opening only elements in the "omdoc:" namespace? Also, schema decisions/problems are an area where @kohlhase always has better advice to offer than me.

**Comment by angerhang** [comment]
I totally misread the manual. I thought the ltx:p was allowed in LaTeXML blocks. 

The reason why we are opening elements in the `ltx:` rather than `omdoc:` is because we are using the `ltxml+omdoc.rnc` for the HTML workflow, which has a default namespace as LaTeXML. I am not entirely sure if my reasoning is plausible though. But Michael gave an example using `ltx:` as the namespace in #112, so probably he can also comment on this.

**Comment by angerhang** [comment]
This ticket is no longer relevant to the new HTML generation approach and thus close.
