### ISSUE TITLE
lmh pdf should copy,  not move the pdf and pdflog files to .../export/... 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#130]
Currently MMT moves the *.pdf and *.pdflog to the ```.../export/...``` dimension of the archive. I am probably the heaviest user of ```lmh pdf``` and mainly use it for development and debugging of course materials. It would be very good if I had access to the log and pdf files in the same directory.

**Comment by kohlhase** [comment]
@tkw1536 should be aware of this.

**Comment by cmaeder** [comment]
MMT is changed to keep *.pdf, *.log and others files in the `source` directory. Only .ltxlog is moved to the `latexml` directory. Does updating lmh help?

**Comment by cmaeder** [comment]
I've no idea about *.pdflog files

**Comment by kohlhase** [comment]
*.pdflog was the pdflatex log files that lmh made so far. 
maybe the log files are now *.log. You should know.

**Comment by cmaeder** [comment]
The .log file should be sufficient, but I now also create a .pdflog file showing the output of calling `xelatex` under `source`.

**Comment by cmaeder** [comment]
the same output will also be part of a .err file under the `errors` folder.
