### ISSUE TITLE
html branch: XHTML better format-not valid tag <resource>

### ISSUE THREAD

**Issue by angerhang** [KWARC/sTeX#133]
The output of XHTML branch is not valid because of the extra `<resource>` tag, and also its information has already been included in the header, and thus should be deleted. 

```xhtml
<?xml version="1.0"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title/>

<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8"/>
<link rel="stylesheet" href="LaTeXML.css" type="text/css"/>
<link rel="stylesheet" href="ltx-article.css" type="text/css"/>
</head>
<body>
<div class="ltx_page_main">
<div class="ltx_page_content">
  <resource xmlns="http://dlmf.nist.gov/LaTeXML" src="LaTeXML.css" type="text/css"/>
  <resource xmlns="http://dlmf.nist.gov/LaTeXML" src="ltx-article.css" type="text/css"/>
  <para xmlns="http://dlmf.nist.gov/LaTeXML" class="theory" xml:id="p1">

    <block class="definition" xml:id="foo">
      <p xmlns:stex="http://kwarc.info/ns/sTeX" xml:id="foo.p1" about="#foo.p1" stex:srcref="/Users/yuancalvin/lmh/localmh/ext/sTeX/htmltest/test.tex#textrange(from=9;0,to=11;16)">
testing </p>
    </block>
  </para>


</div>
<div class="ltx_page_footer">
<div class="ltx_page_logo">Generated  by <a href="http://dlmf.nist.gov/LaTeXML/">LaTeXML <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAOCAYAAAD5YeaVAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wKExQZLWTEaOUAAAAddEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIFRoZSBHSU1Q72QlbgAAAdpJREFUKM9tkL+L2nAARz9fPZNCKFapUn8kyI0e4iRHSR1Kb8ng0lJw6FYHFwv2LwhOpcWxTjeUunYqOmqd6hEoRDhtDWdA8ApRYsSUCDHNt5ul13vz4w0vWCgUnnEc975arX6ORqN3VqtVZbfbTQC4uEHANM3jSqXymFI6yWazP2KxWAXAL9zCUa1Wy2tXVxheKA9YNoR8Pt+aTqe4FVVVvz05O6MBhqUIBGk8Hn8HAOVy+T+XLJfLS4ZhTiRJgqIoVBRFIoric47jPnmeB1mW/9rr9ZpSSn3Lsmir1fJZlqWlUonKsvwWwD8ymc/nXwVBeLjf7xEKhdBut9Hr9WgmkyGEkJwsy5eHG5vN5g0AKIoCAEgkEkin0wQAfN9/cXPdheu6P33fBwB4ngcAcByHJpPJl+fn54mD3Gg0NrquXxeLRQAAwzAYj8cwTZPwPH9/sVg8PXweDAauqqr2cDjEer1GJBLBZDJBs9mE4zjwfZ85lAGg2+06hmGgXq+j3+/DsixYlgVN03a9Xu8jgCNCyIegIAgx13Vfd7vdu+FweG8YRkjXdWy329+dTgeSJD3ieZ7RNO0VAXAPwDEAO5VKndi2fWrb9jWl9Esul6PZbDY9Go1OZ7PZ9z/lyuD3OozU2wAAAABJRU5ErkJggg==" alt="[LOGO]"/></a></div></div>
</div>
</body>
</html>
```

**Comment by angerhang** [comment]
This has already been fixed. I just want to denote it somewhere for the record. 

Since the problem was caused by the way that `LaTeXML-all-xhtml.xsl` includes other stylesheets, more specifically in LaTeXML's `.xsl` file, it uses `import` rather than `include`, rendering the imported stylesheets having a lower precedence. 

The `htmlpost.xsl` is the root stylesheet, in which the `copy` method will overwrite all the deletion templates from LaTeXM's stylesheets, so that the `<resource>` tag is left in the final XHTML. 

In case we sync our LaTeXML stylesheets in the future, this might cause problem again. Unless Bruce's LaTeXML branch changes all the inclusion methods into `include`. I don't know if this is something that LaTeXML's stylesheets can be enhanced upon? Perhaps @dginev can give more insights  : ))))))

**Comment by dginev** [comment]
If you think LaTeXML should handle XSLT inclusions differently, definitely mention it to Bruce. I haven't had too much interaction with the XSLT universe recently but both Michael and Lukas could offer advice. 

Btw I just merged the KWARC/LaTeXML fork with the latest state of Bruce's LaTeXML, so you should keep your eyes open to any changes to sTeX.

**Comment by angerhang** [comment]
Ok thanks! My lmh has been a while, but I will certainly keep an eye on it :wink:
