### ISSUE TITLE
Rethinking HTML approach 

### ISSUE THREAD

**Issue by angerhang** [KWARC/sTeX#134]
After a discussion with Michael today, we decided we would have to change our original HTML approach, which essentially is to use a light variant `*.sty.ltxml` to generate HTML5 and RDFs. 

The right way of generating HTML is actually to set the schema as `ltxml+omdoc.rnc`, so that the bindings should mostly remain unchanged, and let the post processor do the work. We will need to extend the XLST stylesheet to convert the `ltx+omdoc` format into our desired `xhtml` format.

More specifically, the following things need to be done:
* Cleaning all the `block, para` variants in the bindings.
* Creation of a package `sTeX-ns.sty.ltxml` that manages the namespaces properly.
* Extension of `ltxml+omdoc.rnc` to let the post processor generate corresponding `html` from `omdoc`
* Creation of a general stylesheet that imports both `laTeX2html` and `omdoc2html`.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#39
