### ISSUE TITLE
implement \libinput properly

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#145]
Currently modules.sty.ltxml has a rawtex for ```\libinput```, this should be implemented in perl.

**Comment by angerhang** [comment]
In `feature/libinput` branch, I ended up putting many macros/constructors RawTex in `tikzinput.sty.ltxml` and `metakeys.sty.ltxml`, because after we used `addmetakey` in `tikzinput` package, we haven't got the chance the implement the `metakey` properly yet, ` but `libinput` seems to work now.

**Comment by angerhang** [comment]
Perhaps we should also try to implement `metakey` and `tikzinput` packages afterwards.

**Comment by kohlhase** [comment]
I have to look at the ```tikzinput``` package again. First, it needs to be split into the ```tikzinput-mh.sty.ltxml``` and then I think I can do it without ```\addmetakey```, so we will not have to implement ```metakeys.sty.ltxml``` at all.

**Comment by kohlhase** [comment]
could you please push the libinput implement only?

**Comment by kohlhase** [comment]
then I can fix the ```\mhtikzinput``` stuff and reorganize it.

**Comment by angerhang** [comment]
Yeah I just cleaned it up.

**Comment by kohlhase** [comment]
then please merge into master
