### ISSUE TITLE
pdflatex fails for *.zhs.tex files 

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#147]
@kohlhase @La-Stravaganza since I check the exit code of running pdflatex/xelatex, the `*.zhs.tex` files under smglom/sets fail

```
maeder@lati:/var/data/localmh/MathHub/smglom/sets$ lmh pdf --force --pipe-worker-output source/union.zhs.tex
...
*(./union.zhs.aux) (/usr/local/texlive/2015/texmf-dist/tex/latex/tipa/t3cmr.fd)
ABD: EveryShipout initializing macros
*** you should *not* be loading the inputenc package
*** XeTeX expects the source to be in UTF8 encoding
*** some features of other encodings may conflict, resulting in poor output.

! LaTeX Error: Command `\tilde' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
<*> \begin
          {modnl}[creators=Tianlin]{union}{zhs}
(/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/nameref.sty
...
error: pdflatex: exit code 1
pdflatex-result: failure /path/to/localmh/MathHub/smglom/sets/export/pdflatex/source/union.zhs.pdf
```

(Use `lmh setup --update` to get the latest MMT version.)

In fact, this was the example where Jinbo told me to ignore the exit code and only look at the resulting `.pdf` file. (Due to https://github.com/KWARC/MMT/issues/71 the exit code cannot be ignored. The previous behaviour also shadowed many other problems.)

Also some `.tr.tex` files fail now, i.e. `union.tr.tex`

```
*(./union.tr.aux
! Missing \endcsname inserted.
<to be read again> 
                   \relax 
l.37 \@sref@def{\relax }{page}{1}
...
*
! Package keyval Error: p=500 undefined.

See the keyval package documentation for explanation.
...
```

**Comment by cmaeder** [comment]
also `allpdf` fails now for `all.<lang>.tex` files

```
...
*(./intersection.en.tex (./intersection.tex

! Package modules Error: {Module Name Clash
(modules)                A module with name set was already loaded under the pa
th "set"
(modules)                The imported path "/var/data/localmh/MathHub/smglom/se
ts/source/set" is probably a different module with the
(modules)                same name; this is dangerous -- not importing}{Check w
hether the Module name is correct}.

See the modules package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2 \gimport{set}
                 
)) [4]
...
```

**Comment by kohlhase** [comment]
hmmm, this sounds as if the path canonicalizer has struck again. In the
mathhub-enabled setup, no paths should be canonicalized (or all for that
matter).

Michael


On 15/10/15 12:54, cmaeder wrote:
>
> also |allpdf| fails now for |all.<lang>.tex| files
>
> |... *(./intersection.en.tex (./intersection.tex ! Package modules
> Error: {Module Name Clash (modules) A module with name set was already
> loaded under the pa th "set" (modules) The imported path
> "/var/data/localmh/MathHub/smglom/se ts/source/set" is probably a
> different module with the (modules) same name; this is dangerous --
> not importing}{Check w hether the Module name is correct}. See the
> modules package documentation for explanation. Type H <return> for
> immediate help. ... l.2 \gimport{set} )) [4] ... |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/147#issuecomment-148350426>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
This is interesting, this error message does not come from calbf.sty. So
deleting it there will not help. We have to track this down futher. It
is also interesting that this only appears in chinese. I do not believe
that this is the right fix (but you can convince me otherwise).

On 15/10/15 09:45, cmaeder wrote:
>
> @kohlhase <https://github.com/kohlhase> @La-Stravaganza
> <https://github.com/La-Stravaganza> since I check the exit code of
> running pdflatex/xelatex, the |*.zhs.tex| files under smglom/sets fail
>
> |maeder@lati:/var/data/localmh/MathHub/smglom/sets$ lmh pdf --force
> --pipe-worker-output source/union.zhs.tex ... *(./union.zhs.aux)
> (/usr/local/texlive/2015/texmf-dist/tex/latex/tipa/t3cmr.fd) ABD:
> EveryShipout initializing macros *** you should *not* be loading the
> inputenc package *** XeTeX expects the source to be in UTF8 encoding
> *** some features of other encodings may conflict, resulting in poor
> output. ! LaTeX Error: Command `\tilde' already defined. See the LaTeX
> manual or LaTeX Companion for explanation. Type H <return> for
> immediate help. ... <*> \begin {modnl}[creators=Tianlin]{union}{zhs}
> (/usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/nameref.sty ...
> error: pdflatex: exit code 1 pdflatex-result: failure
> /path/to/localmh/MathHub/smglom/sets/export/pdflatex/source/union.zhs.pdf
> |
>
> (Use |lmh setup --update| to get the latest MMT version.)
>
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/147>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
On 15/10/15 09:45, cmaeder wrote:
>
> In fact, this was the example where Jinbo told me to ignore the exit
> code and only look at the resulting |.pdf| file. (Due to KWARC/MMT#71
> <https://github.com/KWARC/MMT/issues/71> the exit code cannot be
> ignored. The previous behaviour also shadowed many other problems.)
>
So concentrating on the exit code is the right solution after all.

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
On 15/10/15 09:45, cmaeder wrote:
>
> Also some |.tr.tex| files fail now, i.e. |union.tr.tex|
>
> |*(./union.tr.aux ! Missing \endcsname inserted. <to be read again>
> \relax l.37 \@sref@def{\relax }{page}{1} ... * ! Package keyval Error:
> p=500 undefined. See the keyval package documentation for explanation.
> ... |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/147>.
>
I have looked at this, and it seems that \usepackage[turkish]{babel}
interacts unfavorably with something in sTeX. I wonder what happens
there. Jinbo could you investigate?

This may have something to do with the fact that ```turkish.ldf``` makes
the characters ! and : and = active, maybe that wrecks some characters?
```
! Missing \endcsname inserted.
<to be read again>
                   \relax
<*> \begin{modnl}[creators=miko]{union}{tr}
                                          
! Extra \endcsname.
\KV@split ...csname \KV@prefix \@tempa \endcsname
                                                  \ifx \@tempc \relax
\KV@er...
```
It could be that ```turkish.ldf``` and ```keyval.sty``` do not work
together; I think that ```\KV@*``` is ```keyval.sty```. That would be
fatal for the many keyval things we do in sTeX.

But then I wonder why this worked before.

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by La-Stravaganza** [comment]
I will investigate this further.

**Comment by La-Stravaganza** [comment]
Error message: ``! LaTeX Error: Command `\tilde' already defined.``

This is because the macro ``\tilde`` is defined by ``fontspec`` package, more specifically, by ``\DeclareMathAccent{\tilde}   {\mathalpha}{legacymaths}{126}``

A short introduction about ``\DeclareMathAccent`` can be found here: https://www.slac.stanford.edu/comp/unix/package/tex/latex/fntguide/node18.html

In short, ``fontspec`` defined ``\tilde``. I've searched the whole sTeX package, only ``sty/etc/calbf.sty`` defined ``\tilde``, which created the conflict.

After I commented out that line of code in ``calbf.sty``, the error message disappeared.

**Comment by dginev** [comment]
Problems like these are some of the major reasons people hate using LaTeX. Great catch @La-Stravaganza !

**Comment by kohlhase** [comment]
I am still not quite sure where the error comes from. 
I see that in ```MathHub/smglom/meta-inf/lib/pre.tex``` the ```fontspec``` package (why do we need it at all?) is loaded before ```preamble.tex```, which loads ```calbf.sty```. That contains the line 
```\def\tilde{\widetilde}```. And ```\def``` does not complain, so it must be ```\DeclareMathAccent```, but that is already over, no?

**Comment by kohlhase** [comment]
I have looked, and there is only one use of \tilde in all of our sTeX material, so I guess I will go along with deleting that. I have made the change and pushed. closing.
