### ISSUE TITLE
duplicated id problem in notations

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#148]
In 
```
\begin{module}[id=test]
\symdef[name=bar]{bar}{B}
\symdef{bar}[1]{B_{#1}}
\end{module}
``` 
we get the warning
```
Info:malformed:id Duplicated attribute xml:id
	/path/to/localmh/MathHub/MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=6;0,to=6;23)
	Duplicated attribute xml:id
	Using id='bar.syma' on <omdoc:symbol _box="\@symdef@construct@presentatio..." _font="Font[serif,medium,upright,10,b..." name="bar"/>
	id='bar.sym' already set on <omdoc:symbol _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." name="bar" xml:id="bar.sym" about="#bar.sym" stex:srcref="MiKoMH/GenCS/source/codes/en/t..."/>
```
and the result
```
    <omdoc:symbol name="foo" xml:id="foo.sym" about="#foo.sym" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=2;0,to=2;26)"/>
    <omdoc:notation cd="test" name="bar" stex:macro_name="bar" stex:nargs="0" xml:id="test.notation4" about="#test.notation4" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=5;0,to=5;25)">
      <omdoc:prototype>
        <om:OMS cd="test" name="bar"/>
      </omdoc:prototype>
      <omdoc:rendering xml:lang="de">
        <m:mi>B</m:mi>
      </omdoc:rendering>
    </omdoc:notation>
    <omdoc:symbol name="bar" xml:id="bar.syma" about="#bar.syma" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=6;0,to=6;23)"/>
    <omdoc:notation cd="test" name="bar" stex:macro_name="bar" stex:nargs="1" xml:id="test.notation6" about="#test.notation6" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=6;0,to=6;23)">
      <omdoc:prototype>
        <om:OMA>
          <om:OMS cd="test" cr="fun" name="bar"/>
          <omdoc:expr name="arg1"/>
        </om:OMA>
      </omdoc:prototype>
      <omdoc:rendering xml:lang="de">
        <m:msub>
          <m:mi>B</m:mi>
          <omdoc:render name="arg1"/>
        </m:msub>
      </omdoc:rendering>
    </omdoc:notation>
```
It seems that the problem is that LaTeXML/sTeX is making the ```xml:id``` attributes for symbols from the name property. But the two ```\symdefs``` have the same name ```name``` (via overwriting). Maybe using the macroname (which should be unique) is better.

**Comment by angerhang** [comment]
How are the macro names unique here? 
Aren't they both `bar` in this case?
```xml
<omdoc:symbol name="bar" xml:id="bar.sym" about="#bar.sym" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=2;0,to=2;25)"/>
    <omdoc:notation cd="test" name="bar" stex:macro_name="bar" stex:nargs="0" xml:id="test.notation4" about="#test.notation4" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=5;0,to=5;25)"> 
```
```xml
<omdoc:symbol name="bar" xml:id="bar.syma" about="#bar.syma" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=6;0,to=6;23)"/>
    <omdoc:notation cd="test" name="bar" stex:macro_name="bar" stex:nargs="1" xml:id="test.notation6" about="#test.notation6" stex:srcref="MiKoMH/GenCS/source/codes/en/test.tex#textrange(from=6;0,to=6;23)">
```

**Comment by kohlhase** [comment]
yes, and that shows that it is wrong to just use the ```name``` directly for the ```id```. It is probably better to use the macro name (which is much more unique) as the main component for the ```id```.

**Comment by angerhang** [comment]
I am still confused. I should make myself more clear. 

For macro names aren't you referring to `stex:macro_name`?

**Comment by kohlhase** [comment]
Let's talk about this in person, I am here most of the day.

Michael

On 09/11/15 09:20, angerhang wrote:
>
> I am still confused. I should make myself more clear.
>
> For macro names aren't you referring to |stex:macro_name|?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/148#issuecomment-154994399>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
Ah, I see, my example is completely messed up. It should be 
```
\begin{module}[id=test]
\symdef[name=barOp]{bar}{B}
\symdef{bar}[1]{B_{#1}}
\end{module}
```
but I cannot currently build that, due to errors, let's squash those first.

**Comment by kohlhase** [comment]
is that done now?
