### ISSUE TITLE
allow \inlinedef omtext environment

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#150]
In ```MiKoMH/GenCS/source/SML/en/SML-rtfm.omdoc``` we get the error ```malformed: \inlinedef outside a statement!``` when transforming with ```latexml```, even though ```pdflatex``` accepts this. 

The offending part is 
```
    \begin{omtext}
      \inlinedef{\defi{RTFM} (\hateq ``read the fine manuals''})
    \end{omtext}
```
I am not sure why this is, since in ```statemts.sty.ltxml``` the conditional is 
```
 my $statement_ancestor = $document->findnode('./ancestor::omdoc:CMP/..', $original_node);
```
and an ```omtext``` environment certainly generates a CMP. Could this be a timing issue?

**Comment by angerhang** [comment]
This does seem to be a timing issue for two reasons:
```tex
\begin{example}
      \inlinedef[for={Boolsort,BoolTrueConst,BoolFalseConst}]
\end{example}
```
in `MiKoMH/GenCS/source/adt/en/adt-def.tex` has no problem finding CMP, so the findnode is able to find `omdoc:CMP` if there is one.

And the second reason what you said: `CMP` exists in the final output.

**Comment by kohlhase** [comment]
so, can you solve it?

**Comment by angerhang** [comment]
Actually I suspect in `omtext.sty.ltxml` if
```
Tag('omdoc:CMP', autoClose=>1, autoOpen=>1);
```
is openning `omdoc:CMP` early enough @dginev ?

How can we make `CMP` open more promptly?

This is part of the `$document` at the time of `findNode`
```xml
  <para xmlns="http://dlmf.nist.gov/LaTeXML" _autoclose="1" _box="LaTeXML::Core::Whatsit=HASH(0x9016258)" _font="Font[serif,medium,upright,10,black,white,1,T1,de,*,*]" _vertical_mode_="1" xml:id="SML-rtfm.omgroup2.p1"/>
  <omtext _box="LaTeXML::Core::Whatsit=HASH(0x987b158)" _font="Font[serif,medium,upright,29.8,black,white,1,T1,de,*,*]" about="#SML-rtfm.omgroup2.omtext3" stex:srcref="/path/to/localmh/MathHub/MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=6;1,to=6;19)" xml:id="SML-rtfm.omgroup2.omtext3"/>
</omgroup>
```
`CMP` is clearly not present.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#37
