### ISSUE TITLE
getNode Box fatal error

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#151]
When I run ```lmh omdoc``` on ```MiKoMH/GenCS/source/machines/en/UTM.tex```, then I get the error
```
Fatal:perl:die Perl died
	Perl died
	Can't call method "getNodeBox" on an undefined value at /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 289.
	In Post::Graphics[@0x8706d00] ->processGraphic
Status:conversion:3 
``` 
this also happens at a couple of other locations in GenCS.

**Comment by angerhang** [comment]
This one can be fixed after https://github.com/brucemiller/LaTeXML/commit/526da1f2466d2973d07eb89e767a2c7fecb586ea  is merged into LaTeXML's KWARC branch.

**Comment by kohlhase** [comment]
@dginev would you please do the merge and/or show @angerhang how to do that?

**Comment by dginev** [comment]
I would rather I kept merging so that I keep my eye on conflicts (and work towards reconciling the fork back with Bruce's master). I just merged and pushed live, feel free to test.

**Comment by kohlhase** [comment]
that makes sense, thanks a lot.

**Comment by kohlhase** [comment]
this seems to work, closing.

**Comment by angerhang** [comment]
This has been fixed.
