### ISSUE TITLE
functions= no longer works

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#154]
it used to be that on a statement you could give the ```functions=``` key and specify some identifiers as functions (so that the LaTeXML parser treats them correctly).  This does not seem to be working any more. We now get the error
```
error: [31;1munexpected:\lxDeclare Attempt to end mode text
```
If I remember correctly, ```functions=``` expands to ```\lxDeclare``` in some way. 
@dginev do you remember?

**Comment by angerhang** [comment]
I wonder if this has to do with #149.
They both attempt to terminate text mode.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#20
