### ISSUE TITLE
DCM/WorkAddress regression

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#155]
It seems that ```dcm.sty.ltxml``` and ```workaddress.sty.ltxml``` do not work together any more. It is not possible to generate OMDoc for problems. Running latexml on ```MiKoProblems/GenCS/source/dmath/en/Geometric_properties.tex``` gives the error
```
Fatal:perl:die Perl died
        /var/data/localmh/MathHub/MiKoProblems/GenCS/source/dmath/en/Geometric_properties.tex#textrange(from=1;1,to=1;15)
        Perl died
        Can't locate object method "new" via package "LaTeXML::KeyVals" (perhaps you forgot to load "LaTeXML::KeyVals"?) at /var/data/localmh/ext/sTeX/sty/dcm/dcm.sty.ltxml line 28.
        In Core::Definition::Constructor[\DCMcre... from dcm.sty.ltxml line 30
         <= Whatsit[\DCMcreators,Core::List[Box[t... <= Core::Document[@0x93cbd88] <= Core::Definition::Constructor[\begin{... <= Whatsit[\begin{module},undef,Core::Li... <= Core::Document[@0x93cbd88] <= Core::Definition::Constructor[\begin{... <= Whatsit[\begin{document},undef,Core::... <= Core::Document[@0x93cbd88]
```
This seems to happen on the source 
```
\DCMcreators{tolariu}
```
which refers to 
```
\WAperson[id=tolariu,
           email=t.olariu@jacobs-university.de,
           affiliation={Jacobs University, Bremen}]
          {Tudor Olariu}
```
in ```MiKoProblems/GenCS/lib/WApersons.tex```. The offending code seems to be 
```
sub FishOutMetadata {
  my ($document,$keyvals)=@_;
  foreach my $role(qw(creators contributors)) {
    my $idlist_string=getKeyValue_noDelim($keyvals,$role);
    my @ids = split(/,\s*/, $idlist_string);
    foreach my $id(@ids) {
      my $name = LookupValue('DCM_'.$id.'_name');
      if ($name) {
        my $prop_role = $role;
chop $prop_role if $prop_role;
        $document->insertElement("dc:$prop_role",$name) if $role;
      } else {print STDERR "Warning: no $role with 'id' $id !\n";}
    }
  }
  return;}#$
```
Assigning to Hang, but @dginev probably knows the code best. 

I do not really understand the error message, ```LaTeXML:KeyVals``` should be loaded, since the binding ```keyval.sty.ltxml``` has been loaded. Could this be an activation problem?

**Comment by dginev** [comment]
The error you cited comes from line 28 in dcm.sty.ltxml, as it says:
https://github.com/KWARC/sTeX/blob/master/sty/dcm/dcm.sty.ltxml#L28

And indeed that line of code seems to predate the last big LaTeXML refactoring which moved KeyVals under the ```Core``` subnamespace. The current instantiation of a KeyVal needs to be respectively:
```
 my $keyval = LaTeXML::Core::KeyVals->new('wa@person',T_BEGIN,T_END,('creators'=>$args));
```

as exemplified in LaTeXML here:
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Core/KeyVals.pm#L80

I suggest doing a grep for "LaTeXML::KeyVals" and adding "Core" in all cases that need it.

**Comment by kohlhase** [comment]
thanks deyan, I vaguely remember that. @angerhang could you do that soon?

**Comment by angerhang** [comment]
Sure I will take a look tonight.

**Comment by angerhang** [comment]
Sure I will take a look tonight.

**Comment by angerhang** [comment]
This has been fixed as well.
