### ISSUE TITLE
implement \sref in sref.sty.ltxml

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#159]
The current stubs for that only make the errors shut up. We should think talk about the oref element in OMDoc.

**Comment by angerhang** [comment]
In 7f84c811339dd9f6a7b24281451478e1eafee670, I added a temporary binding for sref. 

What would be the corresponding omdoc for `sref`, if `fallback`, `pre`, and `post` are not allowed as attributes?
```rnc
oref.attribs = id.attribs & attribute href {xsd:anyURI}
oref.model = inline.model
oref = element oref {tref|(oref.attribs & oref.model)}
```

**Comment by kohlhase** [comment]
That's what I meant by 

> We should think talk about the oref element in OMDoc.

**Comment by kohlhase** [comment]
I have been thinking about giving ```oref``` optional children - attributes do not allow MathML, so we need elements. Something like 
```
<oref href="foo">
  <fallback>the FOO</fallback>
  <pre>in </pre>
  <post>!</pre>
</oref>
```
for ```... \sref[pre={in~},post=!,fallback=above]{foo} ...```. 
I have pushed an extension of the OMDoc schema along these lines, cc: @m-iancu

**Comment by angerhang** [comment]
This is done.
