### ISSUE TITLE
stex classes should take mh option that loades the -mh versions. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#169]
and do not forget to add option ```mh``` to all MathHub stuff.

**Comment by kohlhase** [comment]
I have mostly implemented this on the ```mh-classes``` branch. The LaTeX side seems to work, but I would like to have @angerhang implement it fully for the LaTeXML side. This is almost done, except for the options handling, wherever there is a 
```
RequirePackage('structview-mh');### make contingent of the 'mh' option
```
and for the other packges as well. 
And of course we need debugging. 

It would be great, if we could meet between 8 and 10 tomorrow to talk about this.

**Comment by kohlhase** [comment]
with the ```make contingent on the 'mh' option``` I mean that the packages like ```structview-mh``` should only be loaded if ```mh``` option was given to the package (see the LaTeX implementation)

**Comment by angerhang** [comment]
I just pushed the option handlings and of course more debuggings need to be done : )

**Comment by angerhang** [comment]
By debuggings I mean the issues that are not related to the options. 

The options are already tested and I think we can close this.
