### ISSUE TITLE
stex bindings need to pass on the mh option

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#175]
It seems that there is still a problem in the handling of the ```mh``` option in ```*.sty.txml```. Hang has added 
```
DeclareOption('mh', sub {Digest(T_CS('\@mikoslidestrue')); });
```
but this disables the old 
```
DeclareOption(undef, sub {PassOptions('omdoc','cls',ToString(Digest(T_CS('\CurrentOption'))));
                                          PassOptions('mikoslides','sty',ToString(Digest(T_CS('\CurrentOption'))));});
```
```ProcessOptions()``` does not pass the mh option on to ```mikoslides.sty.ltxml``` and ```omdoc.cls.ltxml``` 

HMMMM, I am trying to fix this, but it all extremely messed up. I wonder how this was all supposed to run at any time, ... we should talk about this. 

BTW, we have 43K fatal errors because of this on MathHub.info :-).

**Comment by angerhang** [comment]
Well I think I was plainly being stupid : >

Although I don't know why the handling of `mh` disables the old options handling on `undef`, I think we can try 
```perl
DeclareOption('mh', sub { RequirePackage('mikoslides-mh'); });
```

I will make a patch later today, if this change resolves the problem.

**Comment by kohlhase** [comment]
you have to be careful here, I think that you probably have to do something like 
```
DeclareOption('mh', sub { RequirePackage('mikoslides-mh'); 
                                          PassOptions('mikoslides','sty',ToString(Digest(T_CS('\CurrentOption'))));
});
```
I possibly for tikzinput.sty as well: The options handled specially do not trigger ```DeclareOption(undef, ....``` -- at least that is my understanding.

**Comment by angerhang** [comment]
In fact I am suspicious if this is a LaTeXML bug.
In the preamble we have
```
\documentclass[mh]{smglom}
```
In `smglom` package if we have 
```
DeclareOption('mh', sub {RequirePackage('mathhub'); });
ProcessOptions();
```
`mathhub` package is not being loaded, but if we have 
```
DeclareOption('mh', sub {RequirePackage('mathhub'); });
ExecuteOptions('mh');
ProcessOptions();
```
`mathhub` is loaded. Which can tell us that `mh` option is doing its job, it might just be `ProcessOptions` is not functioning here? @dginev

**Comment by kohlhase** [comment]
I think that this is not an error. As I said above, LaTeX refuses do do any ```\RequirePackage``` before the Processoptions, and that is correct, since otherwise you would not be able to pass options around. 

I am not sure why the version with ExecuteOptions works, but _that_ may be a LaTeXML error. You should use do what I am sketching in the original desription, namely 
```
DeclareOption('mh', sub {Digest(T_CS('\@mikoslidestrue'));             
                                         PassOptions('omdoc','cls',ToString(Digest(T_CS('\CurrentOption'))));
                                         PassOptions('mikoslides','sty',ToString(Digest(T_CS('\CurrentOption'))));});
```
That should do the trick.

**Comment by angerhang** [comment]
After the most recent change, the option handling should do load the packages properly. However there are two things we need to address before merging `mh-classes` branch:
I. The order of loading packages makes the option handling failed: 
```
(Loading profile /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )
(Loading profile /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )

(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.19 sec)
(Loading /path/to/localmh/ext/sTeX/sty/smglom/smglom.cls.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/omdoc/omdoc.cls.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/article.cls.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.20 sec) 0.23 sec)
(Loading /path/to/localmh/ext/sTeX/sty/omdoc/omdoc.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/sref/sref.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/metakeys/metakeys.sty.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/keyval.sty.ltxml... 0.00 sec) 0.02 sec) 0.04 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/xspace.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/sTeX/sty/omtext/omtext.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/modules/modules.sty.ltxml..
```
For the case of `smglom` class, if we trace down the current option passing order, the `mh` option for `modules.sty.ltxml` should be passed by `smglom.sty.ltxml` but `smglom.sty.ltxml` is loaded after `modules.sty.ltxml` and yes as you said, after a package is loaded, the option can't be passed anymore. So I guess we need to change to profile to change the order of loading i guess?

**Comment by angerhang** [comment]
II. The `smglom` class's option never gets activated,

In the `smglom.cls.ltxml` file I added 
```perl
DeclareOption('mh', sub { AssignValue('@smglom' => 1); });
ProcessOptions();
if(LookupValue('@smglom')) {warn "Option activated!";}
```
and it turns out that the option is never be activated  from `smglom.cls.ltxml`

I think there might be two possible reasons for this:
1. `ProcessOptions();` command is not actually doing the processing work.
2.  Perhaps the preambles are not loaded properly so the option is not be given to LaTeXML side.

**Comment by kohlhase** [comment]
It would help me understand what is going on if you told me what file you are testing on.

**Comment by kohlhase** [comment]
I am looking, it seems that ```omdoc.sty.ltxml``` was not passing the ```mh``` option to ```omtext.sty.ltxml```. I fixed that, but it still does not help.

**Comment by kohlhase** [comment]
I am just guessing here, could it be that you have to use 
```
 AssignValue('@smglom' => 1,'global')
```
so that it is visible, I have tried that, but no avail. 
I guess  you will just have to resort to good old debugging with ```print STDERR``` statements. I would add these in the ```DeclareOption ('mh'``` to see how the options travel. Then you can decide which ones they are.

> I think there might be two possible reasons for this:
> 1. ProcessOptions(); command is not actually doing the processing work.
> 2. Perhaps the preambles are not loaded properly so the option is not be given to LaTeXML side.

I find 1. conceivable but not very likely and 2. works well on the LaTeX side. Make sure that you kill the server sufficiently often to avoid caching effects.

**Comment by kohlhase** [comment]
BTW, I dislike the name of the flags e.g. ```@omdoc```, it should be something with ```mh``` in them e.g. ```mh@omdoc```. Please also change that.

**Comment by kohlhase** [comment]
BTW, you can extract all the ```*.ltxml``` files from the ```*.dxt``` without running pdflatex by ```make package``` that saves me time.

**Comment by kohlhase** [comment]
BTW, I regularized and synchronized the module loading structure and given ```stex.sty.ltxml``` option handling.

**Comment by angerhang** [comment]
I tested on ` mv/source/structure.en.tex`
I think the major obstacle is if `ProcessOptions` really work. I put the following 
in `smglom.cls.ltxml`
```
DeclareOption(undef,sub {  AssignValue('mh@smglom' => 1, 'global');
		PassOptions('omdoc','cls', ToString(Digest(T_CS('\CurrentOption'))));
                                         PassOptions('stex', 'sty', ToString(Digest(T_CS('\CurrentOption'))));
			 PassOptions('smglom','sty',ToString(Digest(T_CS('\CurrentOption')))); });

ProcessOptions();
if(LookupValue('mh@smglom')) {warn "mh in Smglom class activated!";}
```
But the helper message doesn't appear. 

I stop the docker completely by 
```
lmh docker stop
lmh docker start
```
so cacheing shouldn't be an issue.

**Comment by angerhang** [comment]
We can use 
```
ExecuteOptions('mh');
```
to test if the options are doing their jobs.

However, even if we do something like 
```
DeclareOption('mh',sub {  AssignValue('mh@smglom' => 1, 'global');});

DeclareOption(undef,sub {  AssignValue('mh@smglom' => 1, 'global');
		PassOptions('omdoc','cls', ToString(Digest(T_CS('\CurrentOption'))));
                                         PassOptions('stex', 'sty', ToString(Digest(T_CS('\CurrentOption'))));
			 PassOptions('smglom','sty',ToString(Digest(T_CS('\CurrentOption')))); });
ExecuteOptions('mh');
ProcessOptions();
if(LookupValue('mh@smglom')) {warn "Smglom class Option activated!";}
```
This `mh` is still not activated unless we have `ExecuteOptions('mh')` to process the option deliberately.

**Comment by angerhang** [comment]
After playing around with the minimal examples. I finally understand why the 'mh' never gets activated here. 
```
(Loading profile /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )
(Loading profile /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )

(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/TeX.pool.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.18 sec)
(Loading /path/to/localmh/ext/sTeX/sty/smglom/smglom.cls.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/omdoc/omdoc.cls.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/article.cls.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.17 sec) 0.20 sec)
(Loading /path/to/localmh/ext/sTeX/sty/omdoc/omdoc.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/sref/sref.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/metakeys/metakeys.sty.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/keyval.sty.ltxml... 0.00 sec) 0.02 sec) 0.03 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/xspace.sty.ltxml... 0.00 sec) 0.07 sec) 0.30 sec)
(Loading /path/to/localmh/ext/sTeX/sty/stex.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/stex-logo.sty.ltxml... 0.02 sec)
(Loading /path/to/localmh/ext/sTeX/sty/statements/statements.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/omtext/omtext.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/modules/modules.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/presentation/presentation.sty.ltxml... 0.01 sec) 0.04 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/lxRDFa.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/latexsym.sty.ltxml... 0.00 sec) 0.11 sec) 0.14 sec)
(Loading /path/to/localmh/ext/sTeX/sty/sproof/sproof.sty.ltxml... 0.02 sec)
(Loading /path/to/localmh/ext/sTeX/sty/cmath/cmath.sty.ltxml... 0.01 sec)
(Loading /path/to/localmh/ext/sTeX/sty/dcm/dcm.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/rdfmeta/rdfmeta.sty.ltxml... 0.02 sec)
(Loading /path/to/localmh/ext/sTeX/sty/workaddress/workaddress.sty.ltxml... 0.01 sec) 0.06 sec) 0.30 sec)
(Loading /path/to/localmh/ext/sTeX/sty/smglom/smglom.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/smultiling/smultiling.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/structview/structview.sty.ltxml... 0.01 sec) 0.58 sec) 0.92 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/amstext.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/amsfonts.sty.ltxml... 0.00 sec) 1.60 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/amsmath.sty.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/amsbsy.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/amsopn.sty.ltxml... 0.00 sec) 0.08 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/amssymb.sty.ltxml... 0.03 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/eurosym.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/sty/wasysym.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/multirow.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/paralist.sty.ltxml... 0.02 sec)
(Loading /path/to/localmh/ext/sTeX/sty/etc/lststex.sty.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/listings.sty.ltxml...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/latex/listings/listings.cfg... 0.02 sec)
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/latex/listings/lstlang1.sty... 0.65 sec)
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/latex/listings/lstlang2.sty... 0.65 sec)
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/latex/listings/lstlang3.sty... 0.60 sec) 5.99 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/color.sty.ltxml... 0.02 sec) 6.06 sec)
(Loading /path/to/localmh/ext/sTeX/sty/etc/lstomdoc.sty.ltxml...
(Processing definitions /path/to/localmh/ext/sTeX/sty/etc/lstomdoc.sty... 0.09 sec) 0.11 sec)
(Loading /path/to/localmh/ext/sTeX/sty/etc/ded.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/sTeX/sty/etc/calbf.sty.ltxml...
(Processing definitions /path/to/localmh/ext/sTeX/sty/etc/calbf.sty... 0.06 sec) 0.07 sec)
(Loading /path/to/localmh/ext/sTeX/sty/hwexam/hwexam.sty.ltxml...
(Loading /path/to/localmh/ext/sTeX/sty/problem/problem.sty.ltxml... 0.02 sec) 0.04 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/url.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/wrapfig.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/colortbl.sty.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/array.sty.ltxml... 0.00 sec) 0.05 sec)
(Loading /path/to/localmh/ext/sTeX/sty/etc/ed.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/babel.sty.ltxml...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel/babel.sty...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel/switch.def... 0.05 sec)
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel-german/ngerman.ldf...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel-german/ngermanb.ldf...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/babel.def.ltxml...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel/babel.def...
(Processing definitions /usr/local/texlive/2015/texmf-var/tex/generic/config/language.def... 0.06 sec) 1.86 sec) 2.34 sec)
Info:latex:\GenericInfo (babel)             
	/usr/local/texlive/2015/texmf-dist/tex/generic/babel-german/ngermanb.ldf#textrange(from=88;0,to=88;24)
	Package babel Info: Making " an active character
 3.71 sec) 4.61 sec) 7.89 sec) 8.37 sec)

latexmls (LaTeXML version 0.8.1 (KWARC fork); revision ee486e9)
processing started Thu Nov 19 12:58:35 2015

(Digesting TeX structure.en...
(Processing content /path/to/localmh/MathHub/smglom/meta-inf/lib/post.tex...
(Processing content /path/to/localmh/MathHub/smglom/mv/source/structure.en.tex...
(Processing content /path/to/localmh/MathHub/smglom/meta-inf/lib/pre.en.tex...
(Processing content /path/to/localmh/MathHub/smglom/mv/source/localpaths.tex... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/inputenc.sty.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/utf8.def.ltxml... 0.00 sec) 0.02 sec)
```
If we look closely here, most of the packages are preloaded before LaTeXML starts to digest `structure.en`, and apparently all the options will malfunction, which means we cannot take advantage of options as long as we are preloading packages.

**Comment by angerhang** [comment]
More concretely, and in respect to the minimal example, the option is only handled if the package is loaded after Digesting Tex

OptionTest.cls.ltxml passes the option to `rec.sty.ltxml` 
```
DeclareOption('test', sub {PassOptions('rec','sty',ToString(Digest(T_CS('\CurrentOption')))); });
ProcessOptions();
RequirePackage('rec');
```

and `rec.sty.ltxml` prints a message if `test` is being passed
```
DeclareOption('test', sub {AssignValue('@newtest' => 1, 'global'); });
ProcessOptions();
if(LookupValue('@newtest')) { warn "option  Activated";}
```

```
Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/wrapfig.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/colortbl.sty.ltxml...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/array.sty.ltxml... 0.00 sec) 0.05 sec)
(Loading /path/to/localmh/ext/sTeX/sty/etc/ed.sty.ltxml... 0.00 sec)
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/babel.sty.ltxml...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel/babel.sty...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel/switch.def... 0.06 sec)
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel-german/ngerman.ldf...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel-german/ngermanb.ldf...
(Loading /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/babel.def.ltxml...
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/generic/babel/babel.def...
(Processing definitions /usr/local/texlive/2015/texmf-var/tex/generic/config/language.def... 0.06 sec) 1.88 sec) 2.35 sec)
Info:latex:\GenericInfo (babel)             
	/usr/local/texlive/2015/texmf-dist/tex/generic/babel-german/ngermanb.ldf#textrange(from=88;0,to=88;24)
	Package babel Info: Making " an active character
 3.77 sec) 4.68 sec) 7.98 sec) 8.46 sec)

latexmls (LaTeXML version 0.8.1 (KWARC fork); revision ee486e9)
processing started Thu Nov 19 12:49:49 2015

(Digesting TeX test...
(Processing content /path/to/localmh/MathHub/smglom/mv/source/test.tex...
(Loading /path/to/localmh/MathHub/smglom/mv/source/optionTest.cls.ltxml...
(Loading /path/to/localmh/MathHub/smglom/mv/source/rec.sty.ltxml...
Warning:perl:option  Activated
	/path/to/localmh/MathHub/smglom/mv/source/rec.sty.ltxml line 8
	at /path/to/localmh/MathHub/smglom/mv/source/rec.sty.ltxml line 8, <$IN> line 3
	In Core::Gullet[@0x49067c0] /path/to/localmh/MathHub/smglom/mv/source/rec.sty.ltxml line 8
 0.00 sec) 0.03 sec) 0.33 sec) 0.36 sec)
｀｀｀

**Comment by angerhang** [comment]
I am not quite sure how to work around other than not preloading all the packages that are in the flow of `mh` option passing.

**Comment by kohlhase** [comment]
Dear Hang,

I think that preloading should interfere with options. This is (for me)
quite clearly a bug in LaTeXML, and you should report it as such.

Generally, preloading should not in any way interfere with the semantics
of the packages, and the options are part of that.

So just make a minimal example and file a report (and cc me).

Michael

On 19/11/15 14:14, angerhang wrote:
>
> I am not quite sure how to work around other than not preloading all
> the packages that are in the flow of |mh| option passing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/175#issuecomment-158053790>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
Possibly we have to preload them with the right options. That should be
doable.
I am trying to change
.../LaTeXML/resources/Profiles/stex-slides-module.opt...


On 19/11/15 20:03, Michael Kohlhase wrote:
> Dear Hang,
>
> I think that preloading should interfere with options. This is (for
> me) quite clearly a bug in LaTeXML, and you should report it as such.
>
> Generally, preloading should not in any way interfere with the
> semantics of the packages, and the options are part of that.
>
> So just make a minimal example and file a report (and cc me).
>
> Michael
>
> On 19/11/15 14:14, angerhang wrote:
>>
>> I am not quite sure how to work around other than not preloading all
>> the packages that are in the flow of |mh| option passing.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/KWARC/sTeX/issues/175#issuecomment-158053790>.
>>
>
> -- 
> ----------------------------------------------------------------------
>  Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
>  Professor of Computer Science  Campus Ring 1, 
>  Jacobs University Bremen           D-28759 Bremen, Germany
>  tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
>  m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
> ----------------------------------------------------------------------

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
Ha, that seems to do the trick.

**Comment by kohlhase** [comment]
Please update LaTeXML, test widely and merge.

**Comment by dginev** [comment]
To confirm, you needed to pass the options during preload and things worked, correct?

I.e. this is not a bug with LaTeXML?

**Comment by kohlhase** [comment]
Indeed, I confirm this.

**Comment by kohlhase** [comment]
this is fixed and the branch landed
