### ISSUE TITLE
LaTeXML: How to use keys outside an optional argument

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#178]
In #177 I have the problem that I want to give key/value arguments to the document environment. But I cannot (for LaTeX reasons) give the ```{document}``` env an optional argument. Therefore I want to use a separate macro ```\documentkeys{id=foo,...}``` in the preamble. That is easy on the LaTeX side, and I can implement 
```
DefConstructor('\documentkeys RequiredKeyVals:omdoc', sub { activatekeys ($_[1]); return; })
```
Where I still need to have a sub ```activatekeys``` that goes over the keys and assigns values to ```document@<key>``` for all of the keys. ```lstlistings.sty.ltxml``` (where I stole the idea) has the sub ```lstActivate``` that does this (and more). 

Now I need to replace the line 
```
      .    "?&GetKeyVal(#1,'id')(xml:id='&GetKeyVal(#1,'id')')"
```
I had in the code for ```{document}``` and make use of the key ```document@id``` in there. 

As in #177, development is on the ```fix-document``` feature branch. 
@dginev please help @angerhang here.

**Comment by kohlhase** [comment]
@angerhang this has highest priority for me at the Moment (together with #177) i.e. to make the ```fix-document``` branch land.

**Comment by dginev** [comment]
Let me know if you need me for anything, it sounds like Michael's description already has the implementation figured out.

**Comment by angerhang** [comment]
@kohlhase did you forget to push the code which makes use of `document@id`? 

Currently `fix-document` branch still has the original 
```
      .    "?&GetKeyVal(#1,'id')(xml:id='&GetKeyVal(#1,'id')')"
```

**Comment by angerhang** [comment]
Or that's what I am supposed to do?

**Comment by kohlhase** [comment]
> Or that's what I am supposed to do?

yes, that is what you should do (together with reading them information in).

**Comment by kohlhase** [comment]
Note that there is also the LaTeXML ```document@ID``` that needs to be taken care of.

**Comment by kohlhase** [comment]
NOTE also that I have moved some of the changes of ```fix-document``` into ```master``` already. So I think we will have some conflicts when you pull onto ```fix-document``` (do not forget to do that).
