### ISSUE TITLE
debug variable class loading in omdoc.cls.ltxml

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#179]
in ```omdoc.cls.ltxml``` the option ```book``` should trigger loading ```book.cls.ltxml```, but I have never really tested it. This should be done. One thing that certainly does not work is that 
```
DeclareOption(undef, sub  {PassOptions('article','cls',ToString(Digest(T_CS('\CurrentOption'))));
                                          PassOptions('omdoc','sty',ToString(Digest(T_CS('\CurrentOption'))));});
```
only passes the options to ```article.cls.ltxml``` That should use the value of ```omdoc@class```

**Comment by kohlhase** [comment]
not top priority, but probably can be done easily while you are at the options stuff anyway.

**Comment by angerhang** [comment]
I think after understanding how LaTeXML handles preloading with options, this should no longer be an issue.

I tested it and it is true that if we preload `omdoc.cls` with `book`, variable class loading will load `book.sty.ltxml`

but concerning your second remark, I don't see how the `undef` option is only being passed to `article.cls`, from the test I ran, the option is also being passed `omdoc.sty`. 

The bug probably results from out previous approach of passing options, but things should be clear now.

**Comment by kohlhase** [comment]
thanks for testing, but the second remark is still true, I think that the second line should be 
```
DeclareOption(undef, sub  {PassOptions('omdoc@cls','cls',ToString(Digest(T_CS('\CurrentOption'))));
                                          PassOptions('omdoc','sty',ToString(Digest(T_CS('\CurrentOption'))));});
```
i.e. ```omdoc@cls``` instead of ```article```. But that also needs to be tested.

**Comment by kohlhase** [comment]
thanks. We seem to be catching up. I guess I will have to open new issues :-).

**Comment by angerhang** [comment]
Seems like to be the case :>
