### ISSUE TITLE
id problems

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#185]
I get lots of fatal errors (both on ```master``` and ```mh-classes```) with id problems. This is an example. 
```
Michaels-MacBook-Pro:source kohlhase$ pkill perl; mrbuild latexml --force --pipe-worker-output piecewise.en.tex
pkill: signalling pid 5215: Operation not permitted
element XMApp: validity error : ID cvar.2 already defined
error: latexml: no omdoc created
latexml-result: failure /Users/kohlhase/localmh/MathHub/smglom/mv/latexml/piecewise.en.omdoc
element XMApp: validity error : ID cvar.2 already defined
Fatal:HTTP:500 Internal Server Error
```
Is this just my system or is this a general thing? If you do not have the same problems, then

**Comment by kohlhase** [comment]
hmmm, it seems that this is just my local setup on my mac. With docker things succeed.

**Comment by kohlhase** [comment]
Deyan told me that Bruce and he will take care of ids eventually.

**Comment by dginev** [comment]
I am seeing these also for the arXiv conversion, but only on my local machine - they are particular to newer versions of libxml. We thought we fixed that some months back, but it seems it is recurring again. Definitely a core LaTeXML issue.
