### ISSUE TITLE
is mhmodnl every used?

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#188]
We have implemented the ```mhmodnl``` environment, and it is not used, certainly not in SMGloM. Does it even make sense? If not it should be removed.

**Comment by cmaeder** [comment]
I did not find any occurrence of `mhmodnl` (only plenty of `\begin{modnl} ... \end{modnl}`)

**Comment by kohlhase** [comment]
Actually, it should be used everywhere, it is a surprise that ```modnl``` actually works in smglom.
