### ISSUE TITLE
notations lost their outer mrow

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#199]
It seems that notations have lost their outer <mrow> element, and as a consequence, they are invalid. 
in ```smglom/source/set.tex``` we get 
```XML
      <omdoc:rendering>
        <m:mo cr="fun">{</m:mo>
        <m:mrow>
          <omdoc:render name="arg1" precedence="neginfty"/>
          <m:mo>&#x2208;</m:mo>
          <omdoc:render name="arg2" precedence="neginfty"/>
        </m:mrow>
        <m:mo cr="fun">|</m:mo>
        <omdoc:render name="arg3" precedence="neginfty"/>
        <m:mo cr="fun">}</m:mo>
      </omdoc:rendering>
```
instead of 
```XML
    <omdoc:rendering>
      <m:mrow>
        <m:mo cr="fun">{</m:mo>
        <m:mrow>
          <omdoc:render name="arg1" precedence="neginfty"/>
          <m:mo>&#x2208;</m:mo>
          <omdoc:render name="arg2" precedence="neginfty"/>
        </m:mrow>
        <m:mo cr="fun">|</m:mo>
        <omdoc:render name="arg3" precedence="neginfty"/>
        <m:mo cr="fun">}</m:mo>
     </m:mrow>
  </omdoc:rendering>
```
as we used to. 

I am not sure whether the mrow is necessary in the presentation process @m-iancu could you comment? If it is not, then I can tweak the schema else, we should reinstate it. @dginev, could you also comment?

**Comment by dginev** [comment]
Doesn't ring any bells of the top of my head, but we should keep in mind Bruce could have introduced some underwater change of behaviour (or Hang could have). I can help debug if it gets hard to figure out if you get really stuck.

One thing I quickly checked is that LaTeXML always generates a wrapping ```<mrow>``` in expressions with at least one operator, so this could be an sTeX regression?

**Comment by kohlhase** [comment]
Actually, @m-iancu said it will be quite simple for him to work without an outer mrow. So I will adapt the OMDoc schema I guess.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#18
