### ISSUE TITLE
add sTeX/examples as regression tests to travis

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#201]
I would like to have them as regression tests. Currently, the LaTeXML does not run through (see #199 and #200), but I hope this will work out.  I guess the regression testing will work via Makefiles.

**Comment by kohlhase** [comment]
Oh, and this is part of #193

**Comment by cmaeder** [comment]
In https://travis-ci.org/KWARC/sTeX/builds/94675339 you can see the differences of the .omdoc files.
(Absolute paths in `srcref` attributes obviously do not compare well.) The test should fail, but `git diff` does not return a non-zero exit code.

**Comment by cmaeder** [comment]
I think, this can be closed. (Failing tests are another problem.)
