### ISSUE TITLE
weird intermittend error

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#205]
in ```MathHub/ODK/lmfdb/source/conductor.en.tex```, I get a fatal error every secondn time: 
```
Michaels-MBP:source kohlhase$ mrbuild latexml --force conductor.en.tex 
error: latexml: no omdoc created
latexml-result: failure /Users/kohlhase/localmh/MathHub/ODK/lmfdb/latexml/conductor.en.omdoc
Michaels-MBP:source kohlhase$ mrbuild latexml --force conductor.en.tex 
latexml-result: success /Users/kohlhase/localmh/MathHub/ODK/lmfdb/latexml/conductor.en.omdoc
Michaels-MBP:source kohlhase$ mrbuild latexml --force conductor.en.tex 
error: latexml: no omdoc created
latexml-result: failure /Users/kohlhase/localmh/MathHub/ODK/lmfdb/latexml/conductor.en.omdoc
Michaels-MBP:source kohlhase$ 
```
It seems to have to do with the line
```
$N=\ProdProp{p}{\text{$p$
        prime}}{\ratpower{p}{\condexp{p}}}$
``` 
If I comment this out, then success every time. Very weird. 
@dginev I guess you should see this.

**Comment by dginev** [comment]
If @angerhang could debug this to the internal bits of code that break, that would be amazing. I am back to full-time working hours now, so I'll have much smaller debugging windows for stex.

**Comment by kohlhase** [comment]
yes, that is exactly the idea.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#15
