### ISSUE TITLE
clean up branches

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#206]
We need to clean up the branches in sTeX. We currently have more than 10, and most of them are stale. 
```git branch -a``` give me the following list. 
```
  remotes/origin/201-example_regression_test
  remotes/origin/HEAD -> origin/master
  remotes/origin/content_mathml
  remotes/origin/feature/libinput
  remotes/origin/html
  remotes/origin/master
  remotes/origin/mh-classes
  remotes/origin/module_fix
  remotes/origin/multiling
  remotes/origin/new_content_mathml
  remotes/origin/new_html
  remotes/origin/notations_to_grammar
  remotes/origin/origin/new_content_mathml
  remotes/origin/rethinking
```
@angerhang Which of these can be removed from your point of view? 
BTW, we can remove them with ```git push origin --delete <branch>``` I have already done so for two that I knew were obsolete

**Comment by angerhang** [comment]
```
remotes/origin/feature/libinput
remotes/origin/mh-classes
remotes/origin/module_fix
remotes/origin/origin/new_content_mathml # since it is identical with remotes/origin/new_content_mathml
```
can be safely deleted which already has be done.

**Comment by angerhang** [comment]
As for `new_html`, `html`, `content_mathml` and `new_content_mathml`, the `new_` branches are continuations of old works, which move over almost all the changes from the old branches. 

The html and CML branches aren't stable yet, so  we might want to keep them all for now.

**Comment by kohlhase** [comment]
> As for new_html, html, content_mathml and new_content_mathml, the new_ branches are continuations of old works, which move over almost all the changes from the old branches.

Ah, I just realize that these branches are obsolete on the sTeX repository in the sense that they only concern the LaTeXML side. What we need to to is to see what the changes are, see which ones are still relevant, and make new branches at https://github.com/KWARC/LaTeXML-Plugin-sTeX/ that contain the relevant parts of the changes and then remove them here. 
@angerhang, could you do that?

**Comment by angerhang** [comment]
Currently is there any dependency between LaTeXML-Plugin-sTeX and the experimental plugin? Or do we have to manually sync these two repositories?

If there is no dependency,  I suppose we should move all the relevant changes into both the plug-in and the experimental one right by creating new branches right?

 This is also related to #209.

**Comment by kohlhase** [comment]
Actually you are right, I did not think. For the content MathML stuff we should probably make a branch of LaTeXML-Plugin-sTex.  For the sTeX-light stuff I am not sure we may even want to make a different plugin? @dginev, what do you think?

**Comment by kohlhase** [comment]
what is the state here?

**Comment by angerhang** [comment]
I just moved over the new-cmml branch and we are left with:
```
Hangs-MBP:sTeX Hang$ git branch -r
  origin/HEAD -> origin/master
  origin/content_mathml
  origin/html
  origin/master
  origin/multiling
  origin/new_html
  origin/notations_to_grammar
  origin/rethinking
```
We can possibly get rid of  `origin/content_mathml` since all the changes have been merged to the plug-in as well. You will probably have a better idea of how to deal with the rest.

**Comment by angerhang** [comment]
All branches remained are from LaTeX side, closing.
