### ISSUE TITLE
move all the sTeX light stuff into LaTeXML-Plugin-sTeX-experimental

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#209]
We should move ```htmltest``` subdir to the LaTeXML-Plugin-sTeX-experimental, see also https://github.com/KWARC/LaTeXML-Plugin-sTeX/issues/50

**Comment by angerhang** [comment]
Miko can you give me the push rights to LaTeXML-Plugin-sTeX-experimental? 
I don't I think push now.

**Comment by kohlhase** [comment]
I think I have done that, please try.

Michael

On 09/02/16 21:31, angerhang wrote:
>
> Miko can you give me the push rights to LaTeXML-Plugin-sTeX-experimental?
> I don't I think push now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/209#issuecomment-182048302>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: mibein42
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by angerhang** [comment]
Now it works. Thanks.

**Comment by angerhang** [comment]
Done.
