### ISSUE TITLE
assertion environment error

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [KWARC/sTeX#226]
So I tried to use the assertion environment inside an existing module:

\begin{mhmodnl}{sorted-lists}{en}
	\begin{assertion}
		Every \trefii{ordered}{list} has a \trefi{permutation} which is \trefii[sorted-list]{sorted}. 
	\end{assertion}
\end{mhmodnl}

but when I try to compile it, I get 
\begin{assertion} on input line 6 ended by \end{STAssEnv}. \end{assertion}

I am assuming this is a bug?

**Comment by kohlhase** [comment]
`assertion` needs a `type` field, e.g. 
```
\begin{assertion}[type=lemma]
```
There are a couple of these, see the `statements` docummentation

**Comment by freifrauvonbleifrei** [comment]
Oh ok, I thought that was optional. thanks!

**Comment by kohlhase** [comment]
yes, the syntax is a bit misleading, but I am too lazy to change it.
