### ISSUE TITLE
symiv printing last argument

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [KWARC/sTeX#227]
It appears that symiv is always printing the last argument when the file is included. 

For example, when I put 
`\usemhmodule[path=laplace-operator]{laplace-operator}`
which contains the line
`\symiv{linear}{partial}{differential}{operator}`, 
"operator" is inserted on that spot.

**Comment by kohlhase** [comment]
that was a copy/paste error, I hope I have fixed that, please test and close.
