### ISSUE TITLE
listings warning

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#39]
In the KWARC branch of LaTeXML I get the warning 
```
(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/listings.sty.ltxml...
Warning:expected:<number> Missing number, treated as zero.
	/Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/listings.sty.ltxml line 1256
	while processing \lstset
	Next token is T_CS[\linewidth]
	In Core::Gullet[@0x7d5040d0] /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/listings.sty.ltxml line 1256
	 <= \lstset RequiredKeyVals:LST <= Core::Stomach[@0x7d5063a0] <= Core::Gullet[@0x7d5040d0] <= ...

(Processing definitions /usr/local/texlive/2014/texmf-dist/tex/latex/listings/listings.cfg...
(Loading /Users/kohlhase/localmh/ext/perl5lib/lib/perl5/LaTeXML/Package/LaTeX.pool.ltxml... 0.28 sec)[#25] 0.31 sec) 1.87 sec)
```
which is a bit annoying. It seems to me that the cause is that we preload ```lststex.sty.ltxml``` in ```stex-module.opt``` without preloading ```LaTeX.pool.ltxml```, which defines ```linewidth```. I am not quite sure why ```LaTeX.pool.ltxml``` is loaded exactly at this time, since ```stex-module.opt``` has the preloads sectino 
```
preload = amsmath
preload = amssymb
preload = eurosym
preload = wasysym
preload = multirow
preload = paralist
preload = lststex
preload = lstomdoc
preload = ded
preload = calbf
preload = hwexam
preload = url
preload = wrapfig
preload = colortbl
preload = [show]ed
preload = cmath
```
I am not sure what to do here, would preloading ```LaTeX.pool.ltxml``` earlier fix the problem without harming?

**Comment by angerhang** [comment]
It works for me, if we preload `LaTeX.pool.ltxml` by 

    preload = LaTeX.pool

And I think you are right on the order of preloading actually leads to this warning, if we load `lststex.sty.ltxml` before we `LaTeX.pool`. The reason why `LaTeX.pool` is loaded here,  is that `LaTeXML` always starts with `LaTeX.pool` loaded if `LaTeX` specific command is recognized.

Here `latexml` realizes it is currently processing `tex` file and has not yet load `LaTeX.pool.ltxml` yet, so that it preload 'LaTeX.pool.ltxml' immediately, which leads to this warning.

**Comment by kohlhase** [comment]
OK, but what is the fix then?

**Comment by angerhang** [comment]
I didn't commit the change, because I wasn't sure which repository to commit to? Should I do that on my branch of LaTeXML and make a pull request to KWARC branch of LaTeXML?
The fix is to add the line below to `stex-module.opt`:
    
    preload = LaTeX.pool

**Comment by kohlhase** [comment]
@dginev please correct me. I think you should make a pull request for the KWARC branch, then Deyan can get it into main LaTeXML.

**Comment by dginev** [comment]
Exactly, KWARC/LaTeXML is the correct repo, the stex profiles are maintained exactly there.

The stex-module profile should be preloading a class file, rather than LaTeX.pool, since LaTeX fragments ought to be rooted in a class (classes provide a bunch of initializers, e.g. for reference numbers). 

Looking at:
https://github.com/KWARC/LaTeXML/blob/master/lib/LaTeXML/resources/Profiles/stex-module.opt

the class used to be ```[notes]mikoslides.cls```, maybe we should use the currently intended class instead?

**Comment by kohlhase** [comment]
hmmm, that is a bit of a problem, since there are two now: ```omdoc.cls``` for the glossary and ```[notes]mikoslides.cls``` for GenCS, ... But I guess ```omdoc.cls``` is better, since ```[notes]mikoslides.cls``` loads that (eventually).

**Comment by dginev** [comment]
You can always:
 * Make two profiles
 * Pass ```--preload=desired_class.cls.ltxml --profile=stex-module``` from the command-line, that will preload the class before handling the profile.

**Comment by dginev** [comment]
I think you and Bruce eventually convinced me that we want to have stackable profiles as well, so that's also a legitimate option.

**Comment by kohlhase** [comment]
I think we should have the generic ```stex-module``` preload ```[book]omdoc.cls```. 
We should have two more profiles then: ```mikoslides-module``` and ```smglom-module```, where the first preloads ```[notes]mikoslides.cls``` and all its dependencies and the second one also ```smglom.sty``` and so on.

**Comment by kohlhase** [comment]
@dginev do we have stackable profiles?

**Comment by dginev** [comment]
At the moment no. But it's easy to add.

**Comment by kohlhase** [comment]
@jucovschi independently has been playing with a profile for smglom, and preloading more significantly speeds up processing. That is another reason for making specific profiles; he will commit his profile to the KWARC branch of LaTeXML soon.

**Comment by kohlhase** [comment]
Then we can clean up the profiles once we have stackable ones.

**Comment by kohlhase** [comment]
@jucovschi I saw that you committed ```smglom.opt``` to KWARC/LaTeXML could you please rename that to ```stex-smglom-module.opt``` and make two new variants  ```stex-omdoc-module.opt``` (preloads ```omdoc.cls```) and ```stex-slides-module``` (preloads ```mikoslides.cls```).

**Comment by jucovschi** [comment]
done.

**Comment by kohlhase** [comment]
@dginev If I understand correctly, then your recent change at https://github.com/brucemiller/LaTeXML/pull/604 fixes this as well?

**Comment by dginev** [comment]
Not sure, haven't tested. That pull request simply makes sure to load the entire listings library, with all listings language definitions, when listings is preloaded. Not sure if that relates to this issue's problem.
