### ISSUE TITLE
switch sTeX over to produce content MathML

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#41]
Currently sTeX produces OpenMath, but we want to switch over to strict content MathML3, which is equivalent, but syntactialy more pleasing. This entails changes in ```modules.sty.ltxml```, ```cmath.sty.ltxml```, and ```presentation.sty.ltxml``` (maybe more; have a look). Of course, this should be developed on a branch. @dginev can give advice.

**Comment by physikerwelt** [comment]
:+1:

**Comment by angerhang** [comment]
@dginev 
The summer might be the best time to tackle this issue. 

I saw there was already a content MathML branch being worked on by you last year and has not been updated lately.

Do you think it would be a good idea for us to keep working on that branch or create a new branch for this issue?

**Comment by angerhang** [comment]
If we decide to work on the existing branch, it probably would be difficult to the do regression test since that branch is quite antediluvian. 

A better approach could be we create a new branch and mimic the corresponding changes. 

What do you think?

**Comment by dginev** [comment]
Wow, first time I hear of code being "antediluvian"!

I didn't get far with that branch, so feel free to start anew.

**Comment by angerhang** [comment]
Hah the use of that word was just a practice of my vocab as I am preparing for GRE these days : )

But I don't know if I am being too naive again that I can't find other things that need to be changed after this pull request https://github.com/KWARC/sTeX/pull/111? 

My approach is to look for mathematical objects level markups with 'om:' namespace, and change it into the counterparts with the 'm:' namespace detailed in 
http://omdoc.org/pubs/omdoc1.2.pdf.

Am I missing something?

**Comment by dginev** [comment]
Try to generate some OMDoc and review the final generated Content Math, comparing it to the original OpenMath version. If you can convince yourself it matches up perfectly, you're probably done.

High level comment, but it's a good end-to-end test. Good luck with the GRE, I hear they are arduous.

**Comment by angerhang** [comment]
Thanks.

Hmm I thought this would be a much more non-trivial task, since Miko mentioned this conversion to me a long time ago. It is good that this can be done. 

Can you help inspect?

**Comment by angerhang** [comment]
@dginev from my understanding, LaTeXML should be able to generate CMML right? 

I did the following changes but it seems to me that sTeX still has __PMML as the output__ which confused me:
- Changed the math mode in `make/Makefile.latexml.vars` so that LaTeXML can produce cmml.


- Added the `cmml` math mode mimicking 'pmml' in xsl. I haven't written `cmml`'s own sty sheet yet, but I have a feeling that we need to do this(?)

I am also aware that we need to change the binding from PMML to CMML, namely the token elements such as  `mi`, `mn` and `mo.`

I hope I don't get this wrong again : ) 

I suspect the way LaTeXML is called might not necessarily be correct. but I did changed the math mode. So I am nonplussed now...... 

Can you comment on this?

**Comment by dginev** [comment]
Careful, the PMML is there for a reason - it is used in the rendering elements to specify the intended display (and in the general case - all notations) of the defined symbols.

The PMML and OpenMath in the classic sTeX setup were disentangled by a follow-up stylesheet which Michael wrote. This stylesheet also needs to evolve to now disentangle PMML and CMML (maybe it already did?).

I don't have time to inspect the details, but Michael has a great overview on the exact expected markup and the stylesheet processing, so he'll be of great help here.

**Comment by kohlhase** [comment]
> Changed the math mode in make/Makefile.latexml.vars so that LaTeXML can produce cmml.
am I right that you want to use Makefiles for debugging? 

We should be careful with this, the Makefiles are very likely outdated. 
I could not find a change on branch ```new_content_math```, did you push? 

>     Added the cmml math mode mimicking 'pmml' in xsl. I haven't written cmml's own sty sheet yet, but I have a feeling that we need to do this(?)
Generally, the sTeX2OMDoc conversion is in three steps: 
1. running ```latexml``` (converts the top-level sTeX stuff to OMDoc and the text-level to LTX, and generates ltx:XMath for Math and notations)
2. running ```latexmlpost``` (generates parallel OpenMath/XMath for Math and PMML/XMath for notations)
3. running ```omdocpost.xsl``` (cleans up OMDoc, converts text-level LTX to OMDoc/HTML, removes XMath)
(only that ```lmh``` does all of that in a single call of ```latexmlc```) so your approach is essentially correct: 
1. add ```--cmml``` to the invocation of ```latexml```, that extends parallel Math with content MathML. I would leave the OpenMath in there for debugging.
2. changing the Math handling (do not select the OpenMath, but the CMML) in ```omdocpost.xsl```. 
This should be mostly. We have to see what happens with the notations. 

> I am also aware that we need to change the binding from PMML to CMML, namely the token elements such as mi, mn and mo.
No, ```latexmlpost``` should do the right thing. 

If you push to the branch, I can see what happens. Please commit a simple test file (e.g. smglom/sets/source/sets.tex) so that we can have a look and criticize.

**Comment by angerhang** [comment]
Michael I just pushed the changes and added a test file to my fork. 

I don't think the `test.omdoc` is right though.

**Comment by kohlhase** [comment]
Hang, I think that we should not use your fork, but the ```new_content_mathml``` branch directly on the sTeX repository. Either use a branch or a fork.

**Comment by dginev** [comment]
I second Michael here, using the main KWARC/sTeX repo is perfectly fine if you are using your own feature branch on it.

 Having to merge over from a fork, to a feature branch, and then to master, is a paranoid level of quality assurance, and likely too much hassle to be worthwhile for you.

**Comment by kohlhase** [comment]
I am quite sure that Jinbo and Hang have push rights.

**Comment by angerhang** [comment]
I agree. 

Using a feature branch in the fork troubles me whenever I want to synchronize between different forks and branches. I will push directly to the new-content-mathml branch from now no.

Thanks for the suggestion.

**Comment by kohlhase** [comment]
I have played with the branch a bit. 

I completed test.tex so that it runs and I have adapted the Makefiles, so that they generate ```test.xml``` (no stylesheet) and ```test.tomdoc``` (applying the stylesheet to ```test.xml```). This should give us more debugging information. 

The main problem still seems to be that ```--cmml``` and ```--pmml``` interfere considerably (excluding each other). 
In classic sTeX we use ```--pmml --om```, the first is needed for the renderings of the notations and the second one for the OpenMath in the formulae, and that works well. 
If we  change to ```--pmml --cmml```, then the renderings of the notations become cmml as well. It seems that postprocessing only generates cmml. I wonder what happened to parallel  markup here? 

@dginev can you help?

**Comment by dginev** [comment]
Er, that should never happen, sounds like a bug.

Can you give me an exact set of commands and an example file, so that I can reproduce quickly? I am generally short on time this week, but this sounds like something I can quickly diagnose and pass over to @angerhang , as long as I can run see the exact LaTeXML setup and bindings being run.

**Comment by kohlhase** [comment]
> Can you give me an exact set of commands and an example file, so that I can reproduce quickly

just check out the ```new_content_mathml``` branch of sTeX, go to the ```cmmltest``` dir and do 
```
make -nB %to see what is happening
make -n
```
that should do the trick.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#35
