### ISSUE TITLE
make \lec work in course notes (from mikoslides.cls)

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#45]
The ```\lec``` macro from ```omtext.sty``` does not work correctly in notes mode (i.e. when the ```mikoslides``` class is called with the option ```notes``` to create the course notes: instead of starting a new line if the argument of ```\lec``` is longer than the available space on the line, it just stays on the line and creates a very overfull hbox. I have no idea why  this is (except that we are faking slides with
mdframed, which seems to behave differently), but we really need to fix this to make the notes more readable.

**Comment by La-Stravaganza** [comment]
Done. I've made a pull request already. 
I have a little trouble with cloning GenCS, when I finished, I will do a full test with GenCS notes and slides.

**Comment by kohlhase** [comment]
That is a very good idea. I will also give it a test.
