### ISSUE TITLE
take care of duplicate reference warnings 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#47]
I often get warnings of the form 
```
[8pdfTeX warning (ext4): destination with the same identifier (name{sre
f@{terminology}@semnet-nutshell@target}) has been already used, duplicate ignored

\AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
                                                  \fi \fi 
l.112 \end{frame}
```
in sTeX log files. They seem spurious (i.e. I do not have duplicate ids in the source). They seem to come from the way I am passing id arguments in ```sref.sty```. I probably have some place, where I fail to initialize and thus an old value is used again -- thus leading to the duplication. I have looked, but never had time to really track this down.

**Comment by La-Stravaganza** [comment]
I made a minimal test case:
```latex
\documentclass[notes,book,titlepage,defindex]{mikoslides}  
\input{localpaths}
\input{\MathHub{MiKoMH/GenCS/lib/preamble}}
\begin{document}
\begin{module}[id=reasoning]
	\begin{definition}[id=theorem.def]
		A \defi{theorem} is a statement about mathematical objects that we {\red{know to be true}}.
	\end{definition}
	\begin{definition}[id=axiom.prelim.def]
		A conjecture that is proven is called a \defi{theorem}.
	\end{definition}
\end{module}
\end{document}
```
which will create a duplicate reference warning: 
```
pdfTeX warning (ext4): destination with the same identifier (name{sref@{theorem
}@reasoning@target}) has been already used, duplicate ignored
```

I think this is caused by using ``\defi{theorem}`` twice.
Any idea about a possible solution for this?

**Comment by La-Stravaganza** [comment]
Update for minimal test case:
```latex
\documentclass{article}
\usepackage{statements}
\usepackage{hyperref}
\begin{document}
\begin{module}[id=reasoning]
	\begin{definition}[id=theorem.def]
		\defi{theorem} and \defi{theorem}
	\end{definition}
\end{module}
\end{document}
```

I guess it's a conflict between hyperref and  one or more packages in sref, modules, omtext and statements.

**Comment by La-Stravaganza** [comment]
I reappear this warning with
```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\hypertarget{blah}{}
\hypertarget{blah}{}
something
\end{document}
```
```
pdfTeX warning (ext4): destination with the same identifier (name{blah}) has be
en already used, duplicate ignored
```

So this warning is signaled by ``hyperref``, when defining the same hypertarget twice or more.

In sref:
```latex
\newrobustcmd\sref@target@ifh[2]{%
  \ifhref%
    \hypertarget{#1}{#2}%
  \else%
    #2%
  \fi%
}%
```

Clearly this part of code lack a detection, I will try to fix this.

**Comment by La-Stravaganza** [comment]
This is solved. I need to change ``statements.dtx``, please merge #121 first.

**Comment by kohlhase** [comment]
indeed, this is solved. closing.
