### ISSUE TITLE
 make proof step labeling work in sproof.sty

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#49]
Labeling of proof steps in ```sproof.sty``` does not work yet. We use a complex system of nested counters to generate th proof labels. The problem here is that when we use ```\sref@label@id```, then we do not generate the labels (and later, the counters are no longer around). I have tried to use ```\edef``` in various variants, but that leads to problems with inaccessibiltiy. We need a new idea here: just using ```\the@pst@label``` is not enough.

**Comment by La-Stravaganza** [comment]
Could you illustrate more clearly here? I saw the example in the documentation, which kind of labeling bugs do you want to fix?
![selection_003](https://cloud.githubusercontent.com/assets/10081485/8227005/d071253a-15a3-11e5-9db1-3a9216f8c02b.png)

**Comment by La-Stravaganza** [comment]
I notice that  the labels will be shown only with ``spfcases`` environment.

To make the labels customizable, how about implementing a new macro, passing some key-val pairs, such as:
 ``\setstyle{prefix=P, delimiter=., number=arabic}``
which will create label style just as the orginal one?

**Comment by La-Stravaganza** [comment]
So I implemented a new command sequence. With
```latex
\setpstlabelstyle{prefix=Pr,delimiter=-,postfix=\checkmark}
```
, labeling could be fancy like this:
![selection_006](https://cloud.githubusercontent.com/assets/10081485/9048997/d34597d2-3a3d-11e5-9a8e-a43fd4485d6c.png)
