### ISSUE TITLE
can we use relative paths in sTeX?

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#50]
A  couple of years ago, we standardized sTeX to use absolute paths, and I have forgotten why. The absolute paths cause a bit of problems with the ```docker``` version of ```lmh```  so may be we want to rethink this decision and try out relative paths again (or understand/document why we needed the absolute paths in the first place). Maybe @dginev can remember?

**Comment by dginev** [comment]
My memory is that sTeX has always used relative paths for module includes, and we have gone through great lengths to make all implications of relative paths acceptable by LaTeXML (e.g. when pointing to images and other resources).

Where are you encountering absolute path problems?

**Comment by kohlhase** [comment]
Actually, you may have misunderstood what I was trying to say. We use relative paths on LaTeXML/output side, but absolute ones in the sTeX. And I do not remember why the latter was. I guess I will have to exeriment a bit more.

**Comment by dginev** [comment]
Here is an import snippet from sets-operations.tex:
```tex
\begin{module}[id=sets-operations,creators=miko]
\importmhmodule[path=dmath/en/sets-introduction,ext=sms]{sets-introduction}
\importmhmodule[path=dmath/en/mathtalk-definitions,ext=sms]{mathtalk-definitions}
\gimport[smglom/smglom]{union}
\gimport[smglom/smglom]{intersection}
\gimport[smglom/smglom]{emptyset}
\gimport[smglom/smglom]{setdiff}
\gimport[smglom/smglom]{powerset}
\gimport[smglom/smglom]{cartesian-product}
\gimport[smglom/smglom]{pair}
```

To me these seem to be relative paths, but I am only now consciously realizing everything has been ported to ```\gimport``` and ```\importmhmodule```, of which I have a lesser technical understanding.

**Comment by kohlhase** [comment]
Yes, ```\gimport``` and ```\importmhmodule``` internally convert to absolute paths, that is just the problem (the problem is partially solved for me, but worth rethinking anyways).

**Comment by kohlhase** [comment]
I think this is no longer releavnt
