### ISSUE TITLE
includeassignment does not treat due and given correctly. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#51]
```LaTeX
\includeassignment[number=3,given=Mar 6.,due=Mar10.]{a2}
``` 
does not lead to a display of the given and due dates. But if you give them on the 
```LaTeX
\begin{assignment}[given=Mar 6.,due=Mar10.]
```
 it works. 
The problem is the ```\given@due``` macro in ```sTeX/sty/hwexam/hwexam.dtx``` that does not take ```\inclassig@due``` into account. 

@La-Stravaganza, this is your first real sTeX assignment. Please read the code and understand as much as you can an then we can look together.

**Comment by kohlhase** [comment]
you should make your private sTeX fork to work on.

**Comment by kohlhase** [comment]
The test case is a file with 

```LaTeX
\documentclass[12pt,notes,hints,pts]{hwexam}
\input{localpaths}
\input{\MathHub{MiKoMH/GenICT-course/lib/preamble}}
\title{General Information \& Communication Technology I (350101) Fall 2014}
\metasetkeys{document}{hwexamtype=Assignment}
\begin{document}
\includeassignment[number=2,given=from,due=to]{a2}
\end{document}
```
where ```a2.tex``` is something of the form 
```LaTeX
\begin{assignment}[title=Data Structures \& Web Documents,given=Sep. 20.,due=Sep. 27.]
unimportant
\end{assignment}
```
in this case, you should get an assignment with given ```from``` and due ```to```. 

If you remove the keys from ```\includeassignment``` you should get the Sep20,,....

**Comment by La-Stravaganza** [comment]
Done. You can find it on my own fork, or I make a pull request?
