### ISSUE TITLE
mikoslides does not do enumerate well

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#53]
The ```beamer.cls``` theme ```beamerthemeJacobs.sty``` that comes with ```mikoslides.cls``` does not do enumeration ```\begin{enumerate}``` well. This should be fixed. 

@La-Stravaganza:  This is a nice intro bug to ```beamer.cls``` and  should be relatively easy to fix.

**Comment by La-Stravaganza** [comment]
In my test case, I didn't see where is the problem:
```latex
\documentclass{mikoslides}
\newcommand{\sample}{Let life be beautiful like summer flowers And Death like autumn leaves.}
\begin{document}
\begin{frame}
\begin{enumerate}
\item \sample
\item \sample
\item \sample
\end{enumerate}
\end{frame}
\end{document}
```
which generates:
![selection_005](https://cloud.githubusercontent.com/assets/10081485/6981961/25bd1776-da0b-11e4-941d-feec8fecfe44.png)

I guess maybe you don't want to type ``\begin{frame}`` and ``\\end{frame}`` in the text?
Besides, without option ``notes`` will lead to a undefined control sequence ``\textleadsto`` in ``omdoc.sty``. I've fixed that.

**Comment by kohlhase** [comment]
Hmmm, then something else is causing this; I will have to investigate more deeply. 

How did you fix the \textleadsto error? That was annoying.

**Comment by kohlhase** [comment]
hmmm, indeed, I cannot reproduce the errors I was seeing, I will reopen when I can. If I can.
