### ISSUE TITLE
generalize mikoslides away from Kohlhase

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#54]
Currently many things are hard-coded in mikoslides (e.g. ```\source``` is ```Michael Kohlhase```) this should be made more customizable, so that the class can be used more widely. We need a design first, then implementation should be relatively easy. Finally, we need to document that in ```mikoslides.dtx```

**Comment by La-Stravaganza** [comment]
I implemented 3 new macros, customize ``\source``, ``slidelogo`` and ``licensing`` respectively.
Sample Usage:
```latex
\setsource{Someone}
\setlicensing[http://www.ubuntu.com]{ubuntu}
\setslidelogo{skype}
```
![selection_002](https://cloud.githubusercontent.com/assets/10081485/8149161/77ec3cd8-12ba-11e5-9579-aec2ffc2a316.png)

I didn't change the default values, so you don't need to change any existing documents.

**Comment by La-Stravaganza** [comment]
Is there any other hard-coded thing I didn't notice?

**Comment by kohlhase** [comment]
looks good. please push.

**Comment by La-Stravaganza** [comment]
Already merged. So we can close this issue now.
