### ISSUE TITLE
\mhinputref generates relative URIs

### ISSUE THREAD

**Issue by m-iancu** [KWARC/sTeX#55]
I.e. it generates
```<omdoc:oref class="expandable" href="../../../../root/localmh/MathHub/MiKoMH/pythagoreantheorem/source/measurements/length"/>```
 instead of 
```<omdoc:oref class="expandable" href="MiKoMH/pythagoreantheorem/source/measurements/length"/>```

Alternatively, I can update the sTeX importer to support relative paths. That is not difficult just that we had previously tried to absolutize all paths. If that is not valuable for sTeX in itself, the importer can take care of it.

**Comment by kohlhase** [comment]
I think that sTeX should be consistent here, so we should try to fix it at this level. But it is not trivial. 
@m-iancu So maybe you can add the relativization code for the moment? 
I had hoped it would just be a case of adding a ```@cannoical_omdoc_path```, but that is already there. I am not sure what goes wrong. Probably @dginev has to help with this again.

**Comment by dginev** [comment]
Just for the record, this is not an absolute path:
```
MiKoMH/pythagoreantheorem/source/measurements/length
```

Rather, it is a relative path from the base of the repository. I remember we liked those a lot, and I still like them a lot, as they read nicest and are not bound to the concrete filesystem.

This is an absolute path:

```
/home/dreamweaver/localmh/MathHub/MiKoMH/pythagoreantheorem/source/measurements/length
```

This is a trivial observation, but using the right language helps with me not getting confused :)

**Comment by kohlhase** [comment]
you are completely right, what we are really looking for is a canonical path (i.e. one that cannot be shortened).

**Comment by m-iancu** [comment]
@dginev indeed, though, in my defense, the base of the mathhub repository is my canonical root :)

**Comment by dginev** [comment]
"Canonical" I can understand, +1 for using that word for these guys.

Any non-canonical behaviour is indeed an sTeX bug, and I would be happy to patch that (time permitting). 

@m-iancu I thought so :) Although I am surprised you are happy to call unqualified paths absolute, in the URI context you still need to have a domain base (I'm guessing ```http://mathhub.info/...something.../```) to get an absolute URI.

**Comment by kohlhase** [comment]
do you also have an idea what goes wrong?

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#27
