### ISSUE TITLE
refactor the perl part of \defi*, \adefi* into a single (maintainable) sub

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#59]
In ```sTeX/sty/statements.sty.ltxml```  we have a lot of duplicate code (indicated above) that needs to be refactored. This should be relatively simple, but useful. I think that we should have a single ```sub``` that does it all and is called with different arguments.

**Comment by angerhang** [comment]
It should be fixed now.

**Comment by kohlhase** [comment]
did you do a regression test it on a meaningful subset of GenCS? If that passes, make a pull request.

**Comment by angerhang** [comment]
There was no obvious problem.

**Comment by angerhang** [comment]
This is done.
