### ISSUE TITLE
carefully check option handling in LaTeXML. 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#62]
I have done some work on the package/class options on the PDFLATEX side of sTeX. I fear that the PDF and XML sides have gone out of sync on the options side (actually I am sure they have). This should be synchronized carefully. In particular the ```\PassOptionsTo{Package,Class}``` logic need to be mimicked in LaTeXML. This is a prerequisite for #61

**Comment by angerhang** [comment]
While I was syncing the `\PassOptionsTo{foo}` on the LaTeXML side, I realized there were numerous packages's LaTeXML were out of date.

@kohlhase, do you think I should also try to fix the options discrepancies that other options have besides `\PassOptionsTo{foo}`?

**Comment by kohlhase** [comment]
yes, please try to get an overview what the discrepancies are and try to fix them.

**Comment by angerhang** [comment]
It is done.
