### ISSUE TITLE
symvariant problem (association of renderings)

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#65]
I noticed a problem in ```.../smglom/functional-analysis/source/norm.tex```. It contains 
```LaTeX
  \symdef[name=norm]{normOp}{|\cdot|}
  \symvariant{normOp}{double}{\Vert\cdot\Vert}
  \symdef{norm}[1]{\mixfixi[nobrackets]{|}{#1}{|}}
  \symvariant{norm}[1]{double}{\mixfixi[nobrackets]{\Vert}{#1}{\Vert}}
```
and yields 
```XML
    <omdoc:notation cd="norm" name="norm">
      <omdoc:prototype>
        <om:OMS cd="norm" name="norm"/>
      </omdoc:prototype>
      <omdoc:rendering>
        <m:mrow>
          <m:mo stretchy="false">|</m:mo>
          <m:mo>&#x22C5;</m:mo>
          <m:mo stretchy="false">|</m:mo>
        </m:mrow>
      </omdoc:rendering>
      <omdoc:rendering ic="variant:double">
        <m:mrow>
          <m:mo>&#x2225;</m:mo>
          <m:mo>&#x22C5;</m:mo>
          <m:mo>&#x2225;</m:mo>
        </m:mrow>
      </omdoc:rendering>
      <omdoc:rendering ic="variant:double">
        <m:mo cr="fun">&#x2225;</m:mo>
        <omdoc:render name="arg1" precedence="neginfty"/>
        <m:mo cr="fun">&#x2225;</m:mo>
      </omdoc:rendering>
    </omdoc:notation>
    <omdoc:notation cd="norm" name="norm">
      <omdoc:prototype>
        <om:OMA>
          <om:OMS cd="norm" cr="fun" name="norm"/>
          <omdoc:expr name="arg1"/>
        </om:OMA>
      </omdoc:prototype>
      <omdoc:rendering>
        <m:mo cr="fun">|</m:mo>
        <omdoc:render name="arg1" precedence="neginfty"/>
        <m:mo cr="fun">|</m:mo>
      </omdoc:rendering>
    </omdoc:notation>
```
as a result. It seems that the second ```\symvariant{norm}[1]``` deposits its ```<rendering>``` into the first ```<notation>``` (it contains a call to ```arg1``` which gives rise to an error); it should go into the second one (I want to distinguish by argumens). I suspect that the problem is that I have given a ```[name=norm]``` to the first ```\symdef[name=norm]{normOp}``` and that gets things confused. 

I am assigning this to @dginev, since it is probably still to difficult for @angerhang 

It could be that we have to redesign the interface here, ... and I would be willing to do that, but maybe you can first have a look.

**Comment by dginev** [comment]
Thanks for moving, will inspect soon.

**Comment by kohlhase** [comment]
wonderful.

**Comment by kohlhase** [comment]
@deyan, I hate to push, but could you have a look at this (soon:-))

**Comment by dginev** [comment]
ok, will try to get it done today

**Comment by kohlhase** [comment]
that would be wonderful

**Comment by dginev** [comment]
I am not seeing that file in smglom. Could you check it it's committed?

**Comment by kohlhase** [comment]
yes, it it committed, you can see it online at https://gl.mathhub.info/smglom/functional-analysis/blob/master/source/norm.tex

**Comment by dginev** [comment]
I am not seeing the functional-analysis repository locally, and lmh seems to break when I try to update. Could you recommend the right lmh command to get that repo?

**Comment by kohlhase** [comment]
I think you should get it with ```lmh install smglom/functional-analysis```. 
Otherwise you can just 
```
cd ...MathHub/smglom
git clone git@gl.mathhub.info:smglom/functional-analysis.git
```
that may need some other repositories, which can be cloned similarly.

**Comment by dginev** [comment]
Ok, took a look. The symvariant is indeed bound to the first applicable notation it find, looking at its name attribute:
```perl
  my ($notation) = $root->findnodes(".//omdoc:notation[\@name='$name' and ".
                                    "preceding-sibling::omdoc:symbol[1]/\@name
                                    = '$name']");
```

I can't understand why the above example should be valid OMDoc. The notations have clashing names, which makes everything very problematic.

**Comment by kohlhase** [comment]
It is not a problem to have multiple notations per symbol. Indeed this is something we want to have.

**Comment by kohlhase** [comment]
I think I know what the problem is. In the LaTeX we group the notations via the TeX macro. In the OMDoc we do not have that level, but need to coordinate the right prototypes with the renderings. 
The problem is that the code you quote above looks for the right name only, but should also take the number of arguments into account. 
We could fix this by adding an attribute ```args=``` and using 
```
  my ($notation) = $root->findnodes(".//omdoc:notation[\@name='$name' and ".
                                    "\@args='$args']");
```

**Comment by dginev** [comment]
Except that we don't record the args on the notation element at the moment.

**Comment by dginev** [comment]
The simplest fix for your example would be to take the last matched notation, rather than the first one, then we have simple shadowing of notations with clashing names. Which would force you to define any variants before you define a notation with a clashing name. 

Now that I think of it, recording the number of arguments as an attribute on the notation element in OMDoc would be one way of adding uniqueness to the notation elements, right now they look completely identical.

**Comment by kohlhase** [comment]
yes, my intention was that we also record the args in the notations. We do have the information right?

**Comment by dginev** [comment]
Hm, it turns out the attribute name is ```nargs``` and it doesn't make it to the OMDoc, but is present in the intermediate XML representation. Should be done with this in a little bit.

**Comment by dginev** [comment]
I may need to add the attribute to the ```omdoc:notation``` schema definition, or use a ```stex:nargs``` attribute instead. It seems LaTeXML is quite strict with following the schema, as the ```nargs``` attribute gets dropped from the DOM quite early right now.

**Comment by kohlhase** [comment]
I guess ```stex:nargs``` is the best for now.

**Comment by dginev** [comment]
Fixed via a467c19d8e94d61284a43a920e42dec29010808b
@angerhang should be able to understand the changes, it's a very nice example of an sTeX enhancement:
 * I moved the ```macro_name``` and ```nargs``` attributes into the foreign ```stex:``` namespace, which allowed them to get recorded onto the final OMDoc (as they aren't in the OMDoc schema and were being thrown out)
 * Next, I extended the XPath that was obtaining the notation for ```\symvariant``` to also check the number of arguments of the notation, as per Michael's suggest, removing the ambiguity of attachment.
* This presupposes that there won't be clashing notations with the same name and number of arguments btw.
 * Lastly, on a low-level Perl note, I made certain that the ```$nargs``` variable is always given a "0" value when undefined, and wrapped it in double-quotes when passing it to the XML construction in ```->openElement```, to ensure the 0 gets recorded properly in the attribute. If evaluated as an integer, Perl would treat 0 as ```false```, which sometimes lead to undesired behaviours. 

Closing here, should work now.

**Comment by kohlhase** [comment]
@dginev thanks a lot. 
@angerhang please have a look at the problem solution (once the finals are over).

**Comment by angerhang** [comment]
Will take a look after my last final on Thursday : )

**Comment by dginev** [comment]
Best of luck with wrapping up finals to both @angerhang and @La-Stravaganza ! Don't do too much sTeX until you're finished :)

**Comment by angerhang** [comment]
Haha thanks Deyan.

**Comment by La-Stravaganza** [comment]
Thanks!

**Comment by kohlhase** [comment]
I second @dginev's sentiment! good luck.

**Comment by angerhang** [comment]
Thank you too Michael : )

**Comment by angerhang** [comment]
Hmm one question came to my mind, when I looked at the solution to this issue.

Similar to how LaTeXML processes `$nargs` which gets dropped from the DOM, how do we know when one `element | attribute` gets generated and when this `element | attribute` gets dropped out?

**Comment by dginev** [comment]
They need to be in the OMDoc schema. Best way to check that is to look at the zoo of ```.rnc``` files which define the schema. There is also a rather impressive "OMDoc book" document that you should read at least partially, so that you get the intuition behind OMDoc. Michael can help with all that.

**Comment by angerhang** [comment]
I see. Thank you.

**Comment by kohlhase** [comment]
sorry, just found the reason, it is not LaTeXML's fault.
