### ISSUE TITLE
Inconsistent sTeX conversion output

### ISSUE THREAD

**Issue by dginev** [KWARC/sTeX#68]
@cmaeder reports:
```
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6241 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6440 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6241 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6241 Apr 16 17:50 union.omdoc
$ run-latexml.sh union.tex && ls -l union.omdoc
No obvious problems
Wrote /var/data/localmh/MathHub/smglom/sets/source/union.omdoc
-rw-rw-r-- 1 maeder maeder 6440 Apr 16 17:50 union.omdoc

The bigger version contains the additional <omdoc:omtext> wrapper element.
 (There are other differences in other files.)
```

**Comment by cmaeder** [comment]
see https://github.com/KWARC/LaTeXML/issues/5#

**Comment by dginev** [comment]
I can reproduce with lmh, here is the diff:
```xml
<     <omdoc:metadata xml:id="union.metadata1" about="#union.metadata1" stex:srcref="/home/dreamweaver/localmh/MathHub/smglom/sets/source/union.tex#textrange(from=1;0,to=19;12)">
<       <dc:creator xml:id="union.metadata1.creator1" about="#union.metadata1.creator1" stex:srcref="/home/dreamweaver/localmh/MathHub/smglom/sets/source/union.tex#textrange(from=1;0,to=19;12)">miko</dc:creator>
<     </omdoc:metadata>
---
>     <omdoc:omtext xml:id="union.omtext1" about="#union.omtext1" stex:srcref="/home/dreamweaver/localmh/MathHub/smglom/sets/source/union.tex#textrange(from=1;0,to=19;12)">
>       <omdoc:metadata xml:id="union.omtext1.metadata1" about="#union.omtext1.metadata1" stex:srcref="/home/dreamweaver/localmh/MathHub/smglom/sets/source/union.tex#textrange(from=1;0,to=19;12)">
>         <dc:creator xml:id="union.omtext1.metadata1.creator1" about="#union.omtext1.metadata1.creator1" stex:srcref="/home/dreamweaver/localmh/MathHub/smglom/sets/source/union.tex#textrange(from=1;0,to=19;12)">miko</dc:creator>
>       </omdoc:metadata>
>     </omdoc:omtext>
```

It is not a daemon bug, most likely an issue with the sTeX schema or post-processing.

**Comment by dginev** [comment]
This is actually the opposite of a daemon bug - while the same instance of latexmls is running, the output is consistently the same. However, upon starting a new latexmls instance, there is a chance that either output could be generated.

That leads me to think that the way the sTeX schema is being read in by LaTeXML has some non-deterministic element.

**Comment by cmaeder** [comment]
Another odd example is emptyset.tr.tex where the line `error : string is not in UTF-8` is emitted sometimes eight times and other times nine times. (Only a single character is actually wrong.)

```
$ run-latexml.sh emptyset.tr.tex
error : string is not in UTF-8
error : string is not in UTF-8
error : string is not in UTF-8
error : string is not in UTF-8
error : string is not in UTF-8
error : string is not in UTF-8
error : string is not in UTF-8
error : string is not in UTF-8
1 error
Wrote /var/data/localmh/MathHub/smglom/sets/source/emptyset.tr.omdoc
```

**Comment by dginev** [comment]
I have tracked the naive LaTeXML bug and sent a patch to Bruce. For next time, file as an sTeX issue from the start, naming an example file and the diff.

**Comment by cmaeder** [comment]
I still get differences after https://github.com/KWARC/LaTeXML/commit/2712b60f416cec8dd419cb63de32faef7a681587 and https://github.com/KWARC/sTeX/commit/46de899602a6688efe7e55423791fb406d5b6756

```
12c12
<     <omdoc:definition for="defeq?definiens approxeq?approximately-equal defeq?definitional-equation defeq?definiendum" xml:id="defeq.de.definition3" about="#defeq.de.definition3" stex:srcref="smglom/mv/source/defeq.de.tex#textrange(from=2;1,to=7;18)">
---
>     <omdoc:definition for="defeq?definitional-equation defeq?definiendum defeq?definiens approxeq?approximately-equal" xml:id="defeq.de.definition3" about="#defeq.de.definition3" stex:srcref="smglom/mv/source/defeq.de.tex#textrange(from=2;1,to=7;18)">
```

**Comment by cmaeder** [comment]
and even a third version for `smglom/mv/source/defeq.de.tex`

```
    <omdoc:definition for="defeq?definiendum defeq?definiens defeq?definitional-equation" xml:id="defeq.de.definition3" about="#defeq.de.definition3" stex:srcref="smglom/mv/source/defeq.de.tex#textrange(from=2;1,to=7;18)">
 ```

**Comment by dginev** [comment]
Perfect, I love seeing the reports here! Just pushed 711a139 , should be a fix.

Btw, in case you are curious, the sTeX bugs are caused by a Perl feature for non-deterministic retrieval of hash keys, explained in detail here:
http://blog.booking.com/hardening-perls-hash-function.html

**Comment by cmaeder** [comment]
Yes, thanks, that fixed many differences in smglom/mv (after https://github.com/KWARC/sTeX/commit/9d3eea12f0754cd163a5a21e50d027ef207fd08d)!

It became noticeable slower though, but probably due to Michael's additional changes (see #70)

However, there are still differences between runs of `latexmlc` that use `latexmls` (via the --expire option) and those that don't (without `--expire=10`). The latter (individual) calls produce shorter omdoc (see first line below).

```
 12c12
<     <omdoc:definition for="defeq?definiendum defeq?definiens defeq?definitional-equation" xml:id="defeq.de.definition3" about="#defeq.de.definition3" stex:srcref="smglom/mv/source/defeq.de.tex#textrange(from=2;1,to=7;18)">
---
>     <omdoc:definition for="approxeq?approximately-equal defeq?definiendum defeq?definiens defeq?definitional-equation" xml:id="defeq.de.definition3" about="#defeq.de.definition3" stex:srcref="smglom/mv/source/defeq.de.tex#textrange(from=2;1,to=7;18)">
```

Actually the entry `approxeq?approximately-equal` looks wrong in `defeq.de.omdoc` and can only be explained by a prior run of latexmlc on a `approx*.tex` file using the same latexmls instance.

**Comment by cmaeder** [comment]
Even the `.ltlxlog` files are identical if latexmlc is called with the `--quiet` option (otherwise dates and loading times differ)!

**Comment by kohlhase** [comment]
As to the slowdown, I am quite sure that has to do with the retirement of tikz.sty.ltxml, which is not preloaded in ```smglom.opt``` and the others. We should do that. More on this in #70. I guess we can close this issue then.

**Comment by cmaeder** [comment]
Should we not prevent `approxeq?approximately-equal` appearing in `defeq.de.omdoc`? (We could make a new issue, though, if we close this one.)

**Comment by kohlhase** [comment]
Oh, that is correct. Please make a new issue, this is a separate problem.

**Comment by cmaeder** [comment]
@dginev I thought you would close it, but since you did not, I'll do it now.
