### ISSUE TITLE
bug in numberIt

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#69]
We have a new plaything (the MathHub error viewer now runs on GenCS; see https://mathhub.info/mh/common-errors), so we find new bugs in sTeX. Here is the first one. When I run ```latexmlc``` on ```MathHub/MiKoMH/GenCS/source/atp0/en/resolution-example.tex``` I get the error 
```
Fatal:perl:die Perl died
	/path/to/localmh/MathHub/MiKoMH/GenCS/source/atp0/en/resolution-example.tex#textrange(from=23;0,to=23;27)
	Can't call method "getProperty" on an undefined value at /path/to/localmh/ext/sTeX/sty/omtext/omtext.sty.ltxml line 167.
	In Core::Document[@0x6a430f8] EOF?
	 <= Alignment[] <= Core::Document[@0x6a430f8] <= \@open@alignment SkipSpaces DigestedBody <= ...
1 warning; 1 fatal error at /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 69.
```
This is in the ```numberIt``` sub, something to do with computing locators, which surprises me, since we have a separate sub ```locateIt``` just below and this is also called on most of the tags where ```locateIt``` is called. I am assigning it to @dginev (the author) but I would like to have @angerhang to have a look as well to get to know this.

**Comment by kohlhase** [comment]
Oh, I should probably say this happens in 73 other occasions on GenCS. Look for the "Perl died" error in  https://mathhub.info/mh/common-errors

**Comment by angerhang** [comment]
Correct me if I am wrong.
When I run `latexmlc` on `MathHub/MiKoMH/GenCS/source/course/en/grading.tex`
This is the change I made in `numberIt`
```perl
if($whatsit){
print "The right one is:", %$node, "\n";
my $locator = $whatsit->getProperty('locator');
  #Need to inherit locators if missing:
  $locator = (@parents ? $parents[$#parents]->getAttribute('stex:srcref') : '') unless $locator;
  if ($locator) {
    # There is a BUG with namespace declarations (or am I using the API wrongly??) which
    # does not recognize the stex namespace. Hence, I need to redeclare it...
    my $parent=$document->getNode;
    if(! defined $parent->lookupNamespacePrefix("http://kwarc.info/ns/sTeX"))
      { # namespace not already declared?
        $document->getDocument->documentElement->setNamespace("http://kwarc.info/ns/sTeX","stex",0);
      }
$node->setAttribute('stex:srcref'=>$locator);}}
else {
print "The missing one is", %$node, "\n";}return;}
```
I got one entry whose `$whatsit` is not defined (source of Perl' death)

```
The missing document is: about#I1.i2.p1.tabular2.thead5{http://www.w3.org/XML/1998/namespace}idI1.i2.p1.tabular2.thead5
```
I think there has to do with bug with namespace or with some elements that weren't properly wrapped?
I couldn't trace it further.

**Comment by kohlhase** [comment]
what is the state of this issue? Is this fixed with the recent pull request, if so, please close.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#26
