### ISSUE TITLE
latexmls leaks its state into .omdoc output

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#71]
see https://github.com/KWARC/sTeX/issues/68#issuecomment-95105847

`approxeq?approximately-equal` may appear in the `for`-attribute of a `omdoc:definition`-element of `defeq.de.omdoc`, although `defeq.de.tex` is unrelated to i.e. `approxeq.de.tex`. 

I can reproduce it using https://svn.kwarc.info/repos/MMT/src/stex-mmt/run-latexml.sh:

```
run-latexml.sh approxeq.de.tex; run-latexml.sh defeq.de.tex
```

**Comment by cmaeder** [comment]
even repeated names may be generated by latexmls:

```
     <omdoc:definition for="approxeq?approximately-equal approxeq?approximately-equal defeq?definiendum defeq?definiens defeq?definitional-equation equal?equal" xml:id="approxeq.de.definition3"
``` 

Correct is a `for="approxeq?approximately-equal" `.

**Comment by dginev** [comment]
This could be a real bug with latexmls daemonization, those are very valuable to record since having an isolated conversion frame is crucial. Looks pretty interesting, I will investigate soon.

**Comment by kohlhase** [comment]
did anything happen here?

**Comment by cmaeder** [comment]
I've observed this bug now for https://gl.mathhub.info/HelloWorld/smglom.git where we keep the .omdoc files within a test folder to allow comparisons with further runs.

I always get differences when I change the order of building (`--force` versus `--depsFirst`) or do not `--reboot`  (`latexmls`) for a second run. Correct output seems to be produced only with `--expire=-1`.

Usually only the language specific files `{hello,world,helloworld}.{de,en}.omdoc` differ. The proper `for` attributes should only be `"hello?hello hello?hello-function"`, `"world?world"`, and `"helloworld?hello-world-example"` respectively. But due to the latexmls-state the values are sometimes repeated several times and end up in unrelated files.

For example the current file `world.de.omdoc` contains `for="hello?hello hello?hello hello?hello-function hello?hello-function helloworld?hello-world-example helloworld?hello-world-example world?world"` (in an `omdoc:definition` element) only because it is compiled last (via `--force`).

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#25
