### ISSUE TITLE
the latexml server's (latexmlstomp) start directory determines omdoc:imports elements  

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#72]
In order to get comparable omdoc output (for git@gl.mathhub.info:smglom/mv) using https://svn.kwarc.info/repos/MMT/src/stex-mmt/smcomp.py by calling `./smcomp.py mv` the server(s) `latexmlstomp &` must be started in the corresponding "source" directory. If they are started in the parent directory the difference is as follows:

```
11c11
<     <omdoc:imports from="smglom/mv/source/defeq#defeq" xml:id="defeq.de.imports2" about="#defeq.de.imports2" stex:srcref="smglom/mv/source/defeq.de.tex#textrange(from=1;0,to=8;11)"/>
---
>     <omdoc:imports from="smglom/mv/defeq#defeq" xml:id="defeq.de.imports2" about="#defeq.de.imports2" stex:srcref="smglom/mv/source/defeq.de.tex#textrange(from=1;0,to=8;11)"/>
```

I'm not sure what the `from` attribute is supposed to refer to as there are also (independent?) `defeq.tex` and `defeq.en.tex` files.

@jucovschi Futhermore, whenever I start `latexmlstomp &` I get:

```
Name "LaTeXML::Util::Pathname::Pathname_CWD" used only once: possible typo at /var/data/localmh/ext/LaTeXMLStomp/bin/latexmlstomp line 114.
```

**Comment by kohlhase** [comment]
I think we are not using latexmlstomp any more
