### ISSUE TITLE
\text still not quite right

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#74]
I think the issue was on the KWARC LaTeXML fork, so I cannot reopen it now. So I will make it here, since it is between sTeX and LaTeXML. The result of converting ```\text{...}``` is still not quite rigth. In ```MathHub/smglom/numberfields/source/intarith.en.tex``` we have ```\text{$\inset{a}\NegativeIntegerNumbers$```, which yields 
```XML
	  <om:OMATTR>
	    <om:OMATP cd="OMDoc" name="verbalizes">
	      <om:FOREIGN encoding="mtext">
		<om:OMOBJ stex:srcref="Anonymous String#textrange(from=0;1,to=0;0)">
		  <om:OMA>
		    <om:OMS cd="set" name="inset"/>
		    <om:OMV name="a"/>
		    <om:OMS cd="integernumbers" name="negative-integer"/>
		  </om:OMA>
		</om:OMOBJ>
		&#xA0;and&#xA0;
		<om:OMOBJ stex:srcref="Anonymous String#textrange(from=0;1,to=0;0)">
		  <om:OMA>
		    <om:OMS cd="equal" name="equal"/>
		    <om:OMV name="n"/>
		    <om:OMA ic="variant:cdot">
		      <om:OMS cd="intarith" name="multiplication"/>
		      <om:OMI>2</om:OMI>
		      <om:OMV name="k"/>
		    </om:OMA>
		  </om:OMA>
		</om:OMOBJ>
	      </om:FOREIGN>
	    </om:OMATP>
	    <om:OMS cd="OMDoc" name="infObj"/>
	  </om:OMATTR>
```
There are two problems with this. Instead of 
```XML
<om:OMATP cd="OMDoc" name="verbalizes">
...
```
which is invalid OpenMath it should be 
```XML
<om:OMATP>
  <OMS cd="OMDoc" name="verbalizes"/>
 ...
```
and mysteriously, the text node "and" seems wrapped in linebreaks. 
```XML
		&#xA0;and&#xA0;
```
They should also go. 

These two lead to quite a few errors in the SMGloM at the moment.

**Comment by kohlhase** [comment]
@m-iancu fyi

**Comment by cmaeder** [comment]
`&#xa0;` is a non-breaking space equal to `&#160;` or `&nbsp;` (http://en.wikipedia.org/wiki/Non-breaking_space)

**Comment by kohlhase** [comment]
@angerhang could you have a look at this, @dginev should supervise.

**Comment by angerhang** [comment]
Ah didn't know I should take a look, since the assignee is dginev. 

The first problem should be resolved by https://github.com/KWARC/LaTeXML/compare/master...angerhang:master/

Going to inspect the second problem later.

**Comment by angerhang** [comment]
However I encounter a problem about working in the docker.

The primary problem is whenever we make changes in the docker, do we always have to recompile LaTeXML? Is there another way around?

**Comment by angerhang** [comment]
Also currently lmh doesn't allow us to run a LaTeXML fork, so the branch workflow will supplant the fork workflow for lmh I guess?

**Comment by kohlhase** [comment]
I think that ```lmh``` does allow forks, talk to Tom.

**Comment by kohlhase** [comment]
But yes, it would be very good, if you fixed this issue.

**Comment by dginev** [comment]
@dginev is no longer the assignee, have a crack at it :)

**Comment by angerhang** [comment]
@dginev  Hmm I am trapped here. 

I was trying to modify the eventual omdoc by changing OpenMath.pm as LaTeXML makes good omdoc/OpenMath in the post-processing phase right?

But I am not seeing any difference in the output, am I looking at the wrong place?

**Comment by angerhang** [comment]
I made changes in lmh and 
```
lmh shell
cd <PathToLaTexml>
cpanm --notest. 
```
to rebuild LaTeXML

and 
```
lmh gen --localpaths
lmh omdoc intarith.en.omdoc
```
to generate omdoc. 

Perhaps lmh is not responding to the changes that I made?

**Comment by angerhang** [comment]
This is the newly generated output. I think it corresponds to what Michael gave. 

```xml
<om:OMATTR>
  <om:OMATP>
   <om:OMS cd="OMDoc" name="verbalizes"/>
       <om:FOREIGN encoding="mtext">
   <om:OMOBJ stex:srcref="Anonymous String#textrange(from=0;1,to=0;0)">
       <om:OMA>
       <om:OMS cd="set" name="inset"/>
       <om:OMV name="a"/>
       <om:OMS cd="integernumbers" name="negative-integer"/>
    </om:OMA>
</om:OMOBJ>
and
<om:OMOBJ stex:srcref="Anonymous String#textrange(from=0;1,to=0;0)">
    <om:OMA>
        <om:OMS cd="equal" name="equal"/>
        <om:OMV name="n"/>
        <om:OMA> 
            <om:OMS cd="intarith" name="addition"/>
            <om:OMA ic="variant:cdot">
            <om:OMS cd="intarith" name="multiplication"/>
            <om:OMI>2</om:OMI>
            <om:OMV name="k"/>
       </om:OMA>
           <om:OMI>1</om:OMI>
      </om:OMA>
   </om:OMA>
 </om:OMOBJ>
   </om:FOREIGN>
  </om:OMATP>
 <om:OMS cd="OMDoc" name="infObj"/>
</om:OMATTR>
```

**Comment by kohlhase** [comment]
very good, this seems to work now.
