### ISSUE TITLE
numberit problem

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#76]
when I convert ```MathHub/MiKoMH/GenCS/source/course/en/CS-sample-performance.tex``` I get the error:
```
Fatal:perl:die Perl died
	/path/to/localmh/MathHub/MiKoMH/GenCS/source/course/en/CS-sample-performance.tex#textrange(from=96;0,to=96;18)
	Can't call method "getProperty" on an undefined value at /path/to/localmh/ext/sTeX/sty/omtext/omtext.sty.ltxml line 167.
	In Core::Document[@0x68934c8] EOF?
	 <= Alignment[] <= Core::Document[@0x68934c8] <= \@open@alignment SkipSpaces DigestedBody <= ...
1 fatal error at /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 69.
```
I am assigning this to Hang, but @dginev would you please supervise?

**Comment by dginev** [comment]
There are other errors I am seeing in that file, preceding the Fatal, which could be causing an empty whatsit to be generated for that table entry. If that happens, the Fatal would trigger.

The defensive improvement that is needed in any case is to change the calls to ```$whatsit ``` in both numberIt and locateIt, to:
```
my $locator = $whatsit && $whatsit->getProperty('locator');
```
and
```
my $trailer = $whatsit && $whatsit->getProperty('locator');
```

I will let @angerhang add these changes. [Short-circuit evaluation](http://en.wikipedia.org/wiki/Short-circuit_evaluation) is a common idiom in a lot of untyped languages, which protects you from calling methods on undefined values. We use it a lot in LaTeXML.

**Comment by angerhang** [comment]
@dginev @kohlhase thanks for both of your supervisions.

**Comment by angerhang** [comment]
I just submitted a pull request and I think #69 should also be solved with this fix.

**Comment by dginev** [comment]
Btw, a note - we have hidden the Fatal errors, but we haven't resolved the underlying errors. But I think this won't bite us, as the files in question had a number of other error messages generated, so there are plenty of clues to correct the deeper problems.

**Comment by kohlhase** [comment]
I think this is fixed, please close if that is correct.

**Comment by angerhang** [comment]
As Deyan said, we just hid the Fatal error, but for now this can be closed.
