### ISSUE TITLE
inlinedef problem 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#77]
Another undefinedness problem, this time in ```\inlinedef``` in ```MathHub/MiKoMH/GenCS/source/SML/en/SML-prog-effects.omdoc```. This can probably be healed similarly to #76, assigning to Hang, asking @dginev for supervision. 
```
Fatal:perl:die Perl died
	/path/to/localmh/MathHub/MiKoMH/GenCS/source/SML/en/SML-prog-effects.tex#textrange(from=37;75,to=38;20)
	Can't call method "parentNode" on an undefined value at /path/to/localmh/ext/sTeX/sty/statements/statements.sty.ltxml line 285.
	In \inlinedef OptionalKeyVals:omtext{} from statements.sty.ltxml line 309
	 <= \inlinedef{\defi{mutation}: allocatio... <= Core::Document[@0x65daf48] <= ␍\itemize@item\emph{input}/\emph{outp... <= ...
1 error; 1 fatal error at /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 69.
```

**Comment by angerhang** [comment]
Indeed the source of error is the similar to we what have in #76 , calling a function on an empty element, and we can fix it by:
```perl
$statement_ancestor->parentNode->insertBefore($symbolnode,$statement_ancestor) if $statement_ancestor ;
```
I also see this type of protection mechanism appearing for many other cases. 

@dginev shall we make this change, and hopefully solve this by fixing other problems or shall we try to tract this underlying error from here?

**Comment by dginev** [comment]
Note that the defensive treatment is only silencing the error, not fixing it. However, we never want to see Perl die in the middle of conversion, so we should add some kind of defensive mechanism in any case.

But I would advocate for tracing down the exact issue and fixing it now, before we forget about it and have it cause a different surface error. We will add another degree of separation that would need to be uncovered while debugging, so let's not wait until it gets too painful.

**Comment by kohlhase** [comment]
Would it be a good idea to issue a warning or an error here? in the if not branch? That way the problem is still documented.

**Comment by angerhang** [comment]
I was trying to mimic other warning messages, by 
```perl
 if ($statement_ancestor) {
   $statement_ancestor->parentNode->insertBefore($symbolnode,$statement_ancestor);
   } else {
   print STDERR "Warning: 'statement_ancestor' undefined in 'symb' $symb !\n";}}
```
and I got
```
Warning: 'statement_ancestor' undefined in 'symb' mutation !

Warning: 'statement_ancestor' undefined in 'symb' communication !

Warning: 'statement_ancestor' undefined in 'symb' exceptions !
```
which does not point out what the exact warning position is. Is there anything I am missing ?

**Comment by dginev** [comment]
The LaTeXML API has a handy set of methods that you should be using, but this should probably be an error rather than a warning. Here's one example how to invoke Error():
https://github.com/brucemiller/LaTeXML/blob/master/lib/LaTeXML/Package/LaTeX.pool.ltxml#L100

And the general API is documented here:
http://math.nist.gov/~BMiller/LaTeXML/manual/commonmodules/LaTeXML_Common_Error.html

**Comment by angerhang** [comment]
Thanks for the instructions.

I just made a pull request. Would you mind having a look?

**Comment by angerhang** [comment]
@dginev 
I am suspecting 
```perl
 my $xc = XML::LibXML::XPathContext->new( $original_node );
 $xc->registerNs('omdoc', 'http://omdoc.org/ns');
 my ($statement_ancestor) = $xc->findnodes('./ancestor::omdoc:CMP/..');
```
is not finding nodes, but I don't quite know how to see the intermediate result to confirm this. Is there a way to let sTeX generate the intermediate result while generating `*.omdoc`?

**Comment by angerhang** [comment]
I don't know if this will bring any harm or not, but I wonder if it would be cleaner to find nodes using:
```perl
my $statement_ancestor = $document->findnode('./ancestor:omdoc::CMP/..', $original_node);
```

**Comment by dginev** [comment]
Yep, that is the bit of code failing. If you want to take a look at the document, just print it out in that block of code.
```
print STDERR $document->toString;
```

As to your second comment, the reason the code looks ugly is that the obvious APIs were not working the way I expected them to (4-5 years ago). You can try improving, but be prepared to investigate empty results due to unregistered namespaces (the XPath used to always fail without the ```registerNs``` call).

**Comment by angerhang** [comment]
The intermediate results seems overwhelmingly complex. Didn't expected thousands of lines of output, but it does help me with deeper understanding of LaTeXML.

**Comment by angerhang** [comment]
It turns out that, the `findnode` method per se works properly, and thus in the example Michael provides, `MathHub/MiKoMH/GenCS/source/SML/en/SML-prog-effects.omdoc`, `inlinedef` is perfectly fine in `omtext`:
```latex
\begin{omtext}
\inlinedef{\defii{machine}{state}, i.e. the values of variables}. 
\end{omtext}
```
 but not in `itemize`:
```latex
\begin{frame}  
  \frametitle{Programming with Effects on the Machine State}
  \begin{itemize}
    \item \inlinedef{\defi{mutation}: allocation and modification of storage during evaluation}
    \item \inlinedef{\defi{communication}: data may be sent and received over channels}
    \item \inlinedef{\defi{exceptions}: abort evaluation by signaling an exceptional}
  \end{itemize}
\end{frame}
```
because `itemize` doesn't generate node `omdoc:CMP` in `omdoc` but `omtext` does.

**Comment by angerhang** [comment]
After testing if we have something like 
```latex
\begin{omtext}
  \begin{itemize}
    \item \inlinedef{\defi{mutation}: allocation and modification of storage during evaluation}
    \item \inlinedef{\defi{communication}: data may be sent and received over channels}
    \item \inlinedef{\defi{exceptions}: abort evaluation by signaling an exceptional}
  \end{itemize}
\end{omtext}
```
`inlinedef` works fine too. So this bug has something to do with the itemize environment outside of omtext, because `itemlize` environment is no longer encapsulated by `omdoc:CMP` anymore.

So when encountering this kind of situation, shall we create a `omdoc:CMP` node if it is not found or shall we encapsulate `itemlize` environment within `frame` with `omdoc:CMP`?

**Comment by kohlhase** [comment]
The situation is the following (see the OMDoc schema at ```.../ext/sTeX/schema/rnc/omdoc*.rnc``` in particular the "Rich Text" module ```omdocrt.rnc```):
* the ```<o:omtext>```, ```<o:assertion>```, ...  elements (called "statements") have a ```<o:CMP>``` element that acts as a container for ```<h:p>```-like XHTML markup.  
* ```\inlinedef``` (and other inline statements like ```\inlineex```) goes to ```<ltx:text>``` and further to ```<h:span class='inlinedef'>``` in postprocessing. ```\inlinedef``` can occur anywhere inside a statement, i.e. inside its ```<o:CMP>```, in particular nested in a itemization,...  
* the problem with ```\inlinedef``` is that it may also contain ```\defi*```, which generate ```<o:symbol>``` elements which are not allowed in the XHTML rich text, but must be deposited ``outside`` the respective statement (and must be referenced in the ```<h:span>``` element). The ```<o:CMP>``` element is taken as the characteristic marker of the statement element.
For some reason this ```<o:CMP>``` is not found, but it should really really be there already, so we cannot (it would be illegal OMDoc) be just made. We have to find out the real reason why the ```<o:CMP>``` is not found and I just have. The ```\inlinedef``` is not inside a statement (Hang noticed that in #77; but I did not pay attention. 
What we really need is a good error message when we cannot find the ```<o:CMP>```: something like 
```
\inlinedef outside a statement! Try wrapping the paragraph in a 
\begin{omtext}, \begin{assertion}, \begin{axiom}, ... 
whatever is suitable semantically
```
I will make an error message in the LaTeX branch as well, so we should be able to route out these errors. We should close this

**Comment by kohlhase** [comment]
this should be fixed by the recent merge request.
