### ISSUE TITLE
Path Canonicalization

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/sTeX#78]
I found a package called ``currfile`` which could generate the absolute path of a tex file. [Manual here](http://www.ctan.org/pkg/currfile)

Here is a demo usage I made.

```latex
\documentclass{article}
\usepackage[abspath]{currfile}
\begin{document}
\noindent
\input{included}\newline
Relative path of \texttt{test.tex}:

\texttt{\currfilepath} \newline
Absolute path of \texttt{test.tex}: 

\texttt{\currfileabspath} \newline
Absolute path of the folder which contains \texttt{test.tex}: 

\texttt{\currfileabsdir} \newline
\getabspath{included.tex} %store the abs path in \theabspath
Absolute path of \texttt{included.tex}:

\texttt{\theabspath}\newline\newline
But, this doesn't work:\newline
\getabspath{../test/included.tex}
Absolute path of \texttt{../test/included.tex}:

\texttt{\theabspath}
\end{document}
```

which generates:
![selection_019](https://cloud.githubusercontent.com/assets/10081485/7330021/9e55643a-eae7-11e4-9ae2-372b41cc298c.png)

**Note: use ``-recorder`` option when compiling.**

Besides the very last example, it works very well. I'm not sure how we use the path canonicalizer, any advice?

**Comment by kohlhase** [comment]
Good that you are looking around for existing solutions. I was (vaguely) aware of the ```currfile``` package, but i convinced myself that it does not help us. In particular, it 
* does not canonicalize paths. 
* uses the underlying operating system (I do not want that for security concerns). 
I fear that unless you turn up something else, we will need to program canonicalization ourselves.

**Comment by kohlhase** [comment]
this is irrelevant now.
