### ISSUE TITLE
Bug onlyPreamble in LaTeX.pool.ltxml 

### ISSUE THREAD

**Issue by angerhang** [KWARC/sTeX#80]
This is the example I use 
```latex
\documentclass{article}
\usepackage{statements}

\begin{document}
\begin{module}[id=foo]
\importmodule[load=../modules/bar,ext=tex]{bar}
\begin{definition}
\defi{foo}[at=bar,loadmodules] and more

\adefi{FOO}{foo}[at=bar] and more

\end{definition}
\end{module}
\end{document}
```
and I get 
```
Error:unexpected:\usepackage The current command '\usepackage' can only appear in the preamble
	/Users/yuancalvin/stex/example/paper/test.tex#textrange(from=1;12,to=2;11)
	In \usepackage OptionalSemiverbatim Semi... from LaTeX.pool.ltxml line 575
	 <= Core::Stomach[@0x7f92d2ceb598] <= \begin{document} OptionalKeyVals:omdoc <= Core::Stomach[@0x7f92d2ceb598] <= ...
```
which also occurs at 44 places https://mathhub.info/mh/common-errors.

I think the onlyPreamble function doesn't work properly in the following three places from LaTeX.pool.ltxml:
```
 beforeDigest => sub { onlyPreamble('\usepackage'); },
```
```
beforeDigest => sub { onlyPreamble('\RequirePackage'); },
```
```  
beforeDigest => sub { onlyPreamble('\LoadClass'); },
```

**Comment by angerhang** [comment]
This is a perquisite for #61 .

**Comment by angerhang** [comment]
@dginev 
I don't know if this is also a LaTeXML core issue.

**Comment by kohlhase** [comment]
No, this is a ```lmh``` issue, (see
https://github.com/KWARC/localmh/issues/225)

It used to be that ```lmh``` could distinguish between modules and
documents and use the profiles ```stex.opt``` and ```stex-module.opt```
accordingly, now it only uses ```stex-module.opt``` and that leads to
exactly these errors.

On 25/04/15 16:45, angerhang wrote:
>
> @dginev <https://github.com/dginev>
> I don't know if this is also a LaTeXML core issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/80#issuecomment-96217037>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
So all is good (or will be when ```lmh``` is repaired.

**Comment by angerhang** [comment]
I see.

Thanks for the clarification.
