### ISSUE TITLE
finally design a way to handle plurals and inflection in \defi* and \trefi

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#83]
The current situation of marking up defininienda and term references in sTeX has grown over time and needs to be redesigned in the light of our now extensive experience. One of the current problems is handling plurals and inflection. 

## the Status Quo

Currently ```\defi*``` and ```\trefi*``` do not handle plurals and inflections very well - actually at all. We want to say something like "for all groups ..." and have a term reference (via the ```\trefi``` macro)  to the symbol ```group?group``` the word "group". Currently, we do 
```
for all \trefi[groups]{group}s
```
which works for PDF - i.e. it produces the right presentation, but semantically it is quite bad, as 
* the word "groups" is ripped into two pieces, 
* if the term references are hyperlinked, then only the part "group" carries the hyperlink
The situation is definition markup is similar, an example here is "the operation ...  **induces** an operation...". Where we have a plural in the definiens. currently we would mark this up with ```\defi{induce}s```, which has analogous problems as above. 

The current "correct" way of doing this is to make use of the ```\adefi``` and ```\atrefi``` macros, which allow to give "alternative presentation" at the cost of typing more (the first required argument holds the alternative presentation). In the two examples above we have 
* ```\atrefi[groups]{groups}{group}``` and 
* ```\adefi{induces}{induce}```
Generally, the *alternative* form is the semantically adequate one, since in any situation we need to specify the symbol name and the presentation (what goes into the narrative text). BUT in practice (at least in English) the symbol name is often identical with the presentation, so we use the abbreviated form to save typing. And notational convenience is a bit concern, since otherwise the markup is not added in practice. 

But there is another wrinkle, we have another macro that does similar stuff: ```\mtrefi```, which was introduced to deal with the multilingual situation in SGMLoM, it is probably the most semantically complete one. We use if for instance for German: as in ```\mtrefi[groups?group]{Gruppe}```. It does essentially the same as ```\atrefi```, which it was meant to replace, but has a memorable syntax (I think) as it groups the symbol information away from the presentation. 

So we should really think about what a good (i.e. semantically correct and typing-convenient) syntax for definienda and term references could be. This is the purpose of this issue. 

And the problem is non-trivial, here are the current numbers: 
* ```\defi*``` in SMGloM: 1925, in MiKoMH: 2278
* ```\adefi``` in SMMgloM: 83, in MiKoMH: 198
* ```\trefi``` in SMGloM:  1191, in MiKoMH 234
* ```\atrefi``` in SMGloM: 165, in MiKoMH: 93 
* ```\mtrefi``` in SMGloM: 1041.

## What are the problems
1. we cannot handle plurals conveniently (see above)
2. ```\atrefi``` and ```\mtrefi``` do almost the same thing with a bit of a different intuition. Having two forms makes auto/systematic treatment of source (e.g. in ```lmh```) more difficult
3. it is not totally clear whether splitting the compounds into three parts is a good idea. In particular, one of the most common markup errors -- especially in translations is a mismatch between the number of arguments and  the number of ```i``` in the macro. 
4. it is not totally clear what we get semantically out of splitting the compounds into three components; it was initially motivated by better index treatment (thus the ```i```). 
5. are ```\defi*``` and ```\trefi*``` really the best names for the macros? 

## random thoughts towards a solution. 

We could add an optional argument to the end of ```\defi*``` and ```\[a,m]?trefi*``` that is just added. So the plurals example could be marked up as ```\trefi[group]{group}[s]``` and in German as ```\mtrefi[groups?group]{Gruppe}[n]``` with the intuition that the optional argument is "pulled into the presentation". 

We could eliminate/deprecate ```\atrefi*``` in favor of ```\mtrefi*```.

**Comment by wolfram1** [comment]
Dear Michael,

the handling of singular and plural forms with 
     \atrefi 
is short but I'm afraid also to obscure for the normal editor. And you have named the difficulty with linking. So I prefer the full forms of singular and plural forms of a glossary term.
Moreover, your proposal for using 
    \mtrefi 
instead of 
    \atrefi
would be a further simplification of SMGloM (I don't see any disadvantages for the semantic interpretation of the expressions). Ans we should it make as simple as possible.  
What do we do with other special cases, e.g., named mathematical entities with proper nouns?
For example fractional derivatives. There exist different kinds of fractional derivatives which are distinguished by the name of the mathematicans who have defined it, e.g. Caputo fractional derivative. But also Caputo's fractional derivative is often used in the literature.
I'm afraid that we will have a lot of further special cases in the future. Do you see any chance in the future to handle such syntactically similar forms  of a SMGloM entry in an automatic way?
  
 All the best

Wolfram

**Comment by kohlhase** [comment]
[Here is a comment from Heinz that was in my inbox instead of on the
issue tracker. I am adding it here for completeness]


I hope I got everything right which you touch upon.
Notational convenience is certainly "a big concern"
(I hope you mean that at the end of the \adefi-chapter
where you say it's "a bit concern").

I have just begun to reflect on these issues,
I think a quick answer is not easy to give and
the whole bundle of simple little problems has
to be treated carefully to keep things as easy
as possible, and even, if possible,  to make existing
approaches easier.

I have one point that came in my mind when reading
your note:
in the second bulleted text (if the term references ...)
you mention
"the operation ... induces an operation ..."
and then you say that we have here
"a plural in the definiens" and give as an example
\defi{induce}s.

However, that is not a plural form but rather
a conjugated verb form. I see the problem
of other verb forms also occuring in the text.
For instance, for induce possible forms are:
induces, induced, inducing
All these possibilities should to be taken into account.
To me it seems as if the approach you line out in your
random thoughts towards a solution
( \trefi[group]{group}[s] )
is a good starting point. I consider it to be a good
concept to use kind of a stem and to pull whichever
addition is needed into the presentation.
(An empty addition [] might be used by default
to make parsing texts easier?)

The elimination of \atrefi in favour of \mtrefi seems
to be logical to me. \atrefi is at present used in the
en-binding whereas \mtrefi is used in other language
bindings. We could now drop \atrefi and keep only
\mtrefi. \mtrefi does in no way refer to the language
in which it is used.
One might think of a setup of \mtrefi that has
English as default and mentions other languages
in brackets. (Empty brackets [] might stand for
English whereas other languages would have to be
given, like [de], [fr] or [ch].)
I cannot oversee whether for sTeX it is of value to
know about language, it is just an idea.

These are my comments after a first reading.


On 12/05/15 11:51, wolfram1 wrote:
>
> Dear Michael,
>
> the handling of singular and plural forms with
> \atrefi
> is short but I'm afraid also to obscure for the normal editor. And you
> have named the difficulty with linking. So I prefer the full forms of
> singular and plural forms of a glossary term.
> Moreover, your proposal for using
> \mtrefi
> instead of
> \atrefi
> would be a further simplification of SMGloM (I don't see any
> disadvantages for the semantic interpretation of the expressions). Ans
> we should it make as simple as possible.
>
> What do we do with other special cases, e.g., named mathematical
> entities with proper nouns?
> For example fractional derivatives. There exist different kinds of
> fractional derivatives which are distinguished by the name of the
> mathematicans who have defined it, e.g. Caputo fractional derivative.
> But also Caputo's fractional derivative is often used in the literature.
> I'm afraid that we will have a lot of further special cases in the
> future. Do you see any chance in the future to handle such
> syntactically similar forms of a SMGloM entry in an automatic way?
>
> All the best
>
> Wolfram
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/sTeX/issues/83#issuecomment-101218591>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by kohlhase** [comment]
The current state is that I am using ```\defi*s``` and ```\trefi*s``` for simple plurals and ```\ad/trefi``` for everything else. I think this is good enough, closing.
