### ISSUE TITLE
Could we switch the engine from XeLaTeX to LuaTeX?

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/sTeX#84]
The reason why we change from ``pdfLaTex`` to ``XeLaTex`` is that, ``XeLaTeX`` offers a better support for ``UTF-8`` character, which will help us in Chinese module.

``LuaTeX`` also supports this point well, as I tested, no problem dealing with Chinese characters.

As the manual said,

![selection_022](https://cloud.githubusercontent.com/assets/10081485/7571835/7ac80a6e-f81a-11e4-8eba-1cb7db0cdb13.png)

``LuaTeX`` contains full functionality of ``pdfLaTeX``, and it also offers Lua programming possibility. Comparing Lua with TeX,  I would be really appreciate for its elegant programming style. For example,

```latex
\documentclass{article}
\usepackage{luacode}
\begin{document}
A random number:
\begin{luacode}
    tex.print(math.random())
\end{luacode}
\end{document}
```
will generate a random number.

I think ``LuaTeX`` will be a great complement when we deal with complicated problems in the future, other than pure TeX programming.

**Comment by dginev** [comment]
I would advocate strongly against adding lua to the mix of programming capabilities we have, unless there is a very compelling reason to do so. We should strive to simplify when we can, not make things additionally complex.

Why do you need lua?

**Comment by La-Stravaganza** [comment]
Since my recent task is to write a path canconicalizer, probably will use some recursion function. Using tex is a little ugly, so I prefer Lua as an alternative. 

As I said, Lua is only a complement, not for essential parts. Also Lua is much modern than TeX, much easier to create and maintain complicated programs. Pure TeX programming is not intuitive at all, that's why we want to modernize the original source code, I think using Lua could be a nice try.

In which part do you think Lua make things complex?

**Comment by dginev** [comment]
I agree that writing LaTeX programs requires is difficult and horribly out of date with 2015 best practices. However, if you are writing LaTeX packages you should be writing LaTeX, not Lua, Python, Perl, etc. as you are injecting dependencies in the setup. Before you only needed the TeX interpreter, now you need the TeX interpreter + Lua.

That is a trade-off you could *choose* to make, but you should have a good reason to do so. I don't know of a single mainstream package using Lua, as pdflatex continues to be the mainstream interpreter tool, so moving to a Lua dependency would marginalize sTeX to the (possibly tiny) LuaTeX community. I would try to avoid that if possible.

**Comment by La-Stravaganza** [comment]
It is indeed a trade-off, that's why it deserves the discussion here. LuaTeX is integrated in TeXlive(should also in MacTex and MikTex), so the one who install TeXlive will also have LuaTeX, it is just a switch thing. LuaTeX is a superset of pdfLaTeX, so there won't be compatible problems.

LuaTeX is emerging, we all agree that pdfLaTeX is kind of out-dated, even though it is still the mainstream. sTeX won't be used by every LaTeX user, nowadays I believe it's more important to develop sTeX for our own purpose. Lua is something which can significantly save the time and improve efficiency, With Lua we can do more specific optimization quickly and easily, which will eventually benefit all MathHub thing.  

Efficiency is the biggest advantage we get from this trade-off.

**Comment by dginev** [comment]
I was just looking into Michael's dfgprpoposal package today, which apparently has some (partial?) dependency on sTeX. And that package is intended as a mainstream TeX package, apparently used by a lot of researches writing DFG grants.

As I said, personally I would rather not switch over carelessly to a pdflatex-incompatible setup. I am unsure if you really need to have path canonicalization as a TeX function, but if you do there are a number of LaTeX toolbox packages that can make writing one less painful. Usually canonical paths are something that only the OMDoc representation cares for, not sure why they're important in LaTeX.

**Comment by La-Stravaganza** [comment]
Michael insists on that, I also think it is necessary and straightforward to avoid multiple loading. My part of job is to write an individual package, which offers a path canonicalization functionality. Michael will decide which packages in sTeX will use this functionality. It's normally unnecessary for some packages like dfgproposal.

**Comment by dginev** [comment]
Here is an alternative that would allow you to directly copy-paste the path canonicalization code used by LaTeXML while still using pdflatex:
https://www.ctan.org/tex-archive/macros/latex/contrib/perltex

**Comment by La-Stravaganza** [comment]
Thanks, I will take a deep looking.

**Comment by kohlhase** [comment]
Let me chime in on this with two statements: 
* I do not want to make LuaTeX the only engine, it is indeed an interesting approach, but a niche technology without a large community. The reason I support the ```pdflatex``` route at all is that it is (relatively) hassle-free for people to install. One niche technology (LaTeXML) is enough for one project. For the same reason I do not want to use perltex. 
* the implementation of path canonicalization in TeX is not that terrible to do. We only need to bite the bullet and go down to low-level tex to do it properly. If that for some reason cannot be done, I would rather continue without path canonicalization with full absolute paths as we are doing now.

**Comment by kohlhase** [comment]
That being said, it is good that Jinbo is looking for alternatives. But I think that luatex is not one of them.

**Comment by La-Stravaganza** [comment]
I get it. I will focus on the current way.
