### ISSUE TITLE
schema problem

### ISSUE THREAD

**Issue by kohlhase** [KWARC/sTeX#90]
In ```.../MathHub/MiKoMH/GenCS/source/search/en/genetic-algorithms.tex``` I get an error I do not understand. It seems to be a model problem. 
```
(Loading compiled schema /path/to/localmh/ext/sTeX/schema/omdoc+ltxml.model... 0.02 sec)...
Fatal:misdefined:<caller> Should not ask for Qualified Name for node of type 11: XMLFragment[<ltx:inline-block _autoclose="1" _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." _vertical_mode_="1" xmlns="http://dlmf.nist.gov/LaTeXML"/>]
	/path/to/localmh/MathHub/MiKoMH/GenCS/source/search/en/genetic-algorithms.tex#textrange(from=31;0,to=31;59)
	In Core::Document[@0x7e73400] /path/to/localmh/MathHub/MiKoMH/GenCS/source/search/en/genetic-algorithms.tex#textrange(from=31;0,to=31;59)
	 <= \begin{example} OptionalKeyVals:omtext <= \begin{example}[title={Evolving 8 Que... <= Core::Document[@0x7e73400] <= ...
1 warning; 1 fatal error at /path/to/localmh/ext/perl5lib/lib/perl5/LaTeXML/Common/Error.pm line 69.
```
I have no idea what is happening, this may even be a LaTeXML problem?

**Comment by dginev** [comment]
That may well be, @brucemiller does that message ring a bell? Any clues as to why would a ltx:inline-block be inside a libxml XMLFragment ?

**Comment by brucemiller** [comment]
This ended up in my spam folder, and I just noticed it. That's one of libxml2's mysteries, but I suspect that somewhere you (or I) have done something with an xpath that managed to select a fragment of document (multiple nodes) where you were expecting only a single one. If you're using LaTeXML's apis, there's a distinction between findnode and findnodes for that purpose.

**Comment by kohlhase** [comment]
This issue was moved to KWARC/LaTeXML-Plugin-sTeX#24
