### ISSUE TITLE
perl warning for sTeX/sty/statements/statements.sty.ltxml line 286

### ISSUE THREAD

**Issue by cmaeder** [KWARC/sTeX#96]
Currently I'm getting the following .ltxlog outpu for our smglom/mv filest. Should I care about this warning?

```
(Loading profile /var/data/localmh/ext/LaTeXML/blib/lib/LaTeXML/resources/Profiles/stex-smglom-module.opt... )
(Loading profile /var/data/localmh/ext/LaTeXML/blib/lib/LaTeXML/resources/Profiles/stex-smglom-module.opt... )

Warning:perl:warn Perl warning
        /var/data/localmh/ext/sTeX/sty/statements/statements.sty.ltxml line 286
        Unrecognized escape \i passed through at /var/data/localmh/ext/sTeX/sty/statements/statements.sty.ltxml line 286.
        In Core::Gullet[@0x459bc20] /var/data/localmh/ext/sTeX/sty/statements/statements.sty.ltxml line 286
Driver file for pgf: \pgfsysdriver



Conversion complete: 1 warning.

Post-processing complete: No obvious problems
Status:conversion:1
```

**Comment by dginev** [comment]
You should, it means a backslash needs to get escaped. I quickly skimmed statements.sty.ltxml, there should either be single quotes as in ```'\'``` or an escape with double-quotes, as in ```"\\"```.

It's broken here for instance:
https://github.com/KWARC/sTeX/blob/master/sty/statements/statements.sty.ltxml#L286

**Comment by dginev** [comment]
It's minor in this case though, you'll only get a garbled error message.
